#!/usr/bin/perl

#load the blkid cache
open(BLKID,"blkid -s UUID|");
while(<BLKID>) {
  if (/^(\/[\w\/-]+): (.*)/) {
    $uuid{$1}=$2;
#    chop $uuid{$1};
  };
}

#use grub-probe to set the / filesystem 
$myid=`grub-probe -t fs_uuid / 2>/dev/null`;
if ($myid ne "") {
  chop $myid;
  $myid="UUID=\"" . $myid . "\"";
  $passno=1;
  printf "%-45s %-50s %-10s defaults%-20s 0 %s\n",$myid,"/","ext4",",acl,user_xattr",$passno;
} else {
  $passno=0;
}

#read mtab adding other file systems by UUID exclude flash and ram devices
open(MNT,"/etc/mtab");
while(<MNT>) {
  if ((/^\/dev\/mapper\/(flash|lvm-images)/) || (/^\/dev\/(flash|ram|loop)/)) {
    next;
  }

  if (/^(\/[\w\/-]+)\s(\/[\w\/-]+|\/)\s([\w]+)/) {
    if (($2 eq "/boot/images") || ($2 eq "/install/tools") ||
        ($2 eq "/media/isofs") || ($2 =~ /^\/usr\/gnemul/) ||
        ($2 =~ /\/dtsbuild\/build$/) || ($2 =~ /\/dtsbuild\/tar$/) ||
        (! -e $1) || (! -d $2)) {
      next;
    }

    if ($uuid{$1} eq "") {
      $blkid=`blkid -o value -s UUID $1`;
      if ($blkid ne "") {
        chop $blkid;
        $uuid{$1}="UUID=\"" . $blkid . "\"";
      } else {
        $uuid{$1}=$1;
      }
    }

    if (($2 eq "" ) || ($2 eq "/" )) {
      if ($myid ne "") {
        next;
      }
      $passno="1";
      $mpath="/";
    } else {
      $passno="2";
      $mpath=$2;
    }

    if (index($3,"ext") == 0) {
      $opts=",acl,user_xattr";
    } else {
      $opts="";
    }

    printf "%-45s %-50s %-10s defaults%-20s 0 %s\n",$uuid{$1},$mpath,$3,$opts,$passno;
  }
}

open(FSW,"blkid -t TYPE=swap -s UUID |");
while(<FSW>) {
  chop $_;
  if (/^(\/[\w\/]+):\s(.*)/) {
    if (index($1, "/dev/mapper/cryptswap") eq 0) {
      printf "%-45s %-50s %-10s nofail%-22s 0 0\n",$1,"none","swap","";
    } else {
      printf "%-45s %-50s %-10s nofail%-22s 0 0\n",$2,"none","swap","";
    }
  }
}

printf "%-45s %-50s %-10s defaults%-20s 0 0\n","proc","/proc","proc","";
printf "%-45s %-50s %-10s defaults%-20s 0 0\n","devpts","/dev/pts","devpts","";
printf "%-45s %-50s %-10s defaults%-20s 0 0\n","usbfs","/proc/bus/usb","usbfs","";
printf "%-45s %-50s %-10s defaults%-20s 0 0\n","nfsd","/proc/fs/nfsd","nfsd","";

if ( -e "/tftpboot/Ubuntu/desktop-i386.iso") {
  printf "%-45s %-50s %-10s defaults%-20s 0 0\n","/tftpboot/Ubuntu/desktop-i386.iso","/tftpboot/Ubuntu/Desktop/","iso9660",",user,loop,ro";
}

if ( -e "/tftpboot/Ubuntu/server-i386.iso") {
  printf "%-45s %-50s %-10s defaults%-20s 0 0\n","/tftpboot/Ubuntu/server-i386.iso","/tftpboot/Ubuntu/Server/","iso9660",",user,loop,ro";
}

if (-e "/etc/fstab.local") {
  open(LFS,"/etc/fstab.local");
  while(<LFS>) {
    print $_;
  }
  close(LFS);
}

if (-e "/etc/fstab.vault") {
  open(EFS,"/etc/fstab.vault");
  while(<EFS>) {
    print $_;
  }
  close(EFS);
}

