#!/bin/bash

IFS=- read -a KREL <<< $(uname -r)
KSUF=${KREL[2]}

init_rd_drivers() {
  kernel=${3}

  for kdir in drivers drivers-ata drivers-scsi drivers-usb nfs drivers-net;do
    mkdir -p ${1}/lib/modules/${kernel}/${kdir}
  done;

  for atadrv in ata mmc/host memstick/host memstick/core mfd ;do
    if [ -d ${2}lib/modules/${kernel}/kernel/drivers/${atadrv} ];then
      cp -r ${2}lib/modules/${kernel}/kernel/drivers/${atadrv}/* ${1}/lib/modules/${kernel}/drivers-ata
    fi;
  done;

  if [ -d ${2}lib/modules/${kernel}/kernel/drivers/usb/storage ];then
    cp -r ${2}lib/modules/${kernel}/kernel/drivers/usb/storage/* ${1}/lib/modules/${kernel}/drivers-usb
  fi;

  if [ -d ${2}lib/modules/${kernel}/kernel/drivers/net/ethernet ];then
    cp -r ${2}lib/modules/${kernel}/kernel/drivers/net/ethernet/* ${1}/lib/modules/${kernel}/drivers-net
    rm -rf ${1}/lib/modules/${kernel}/drivers-net/sfc*
    rm -rf ${1}/lib/modules/${kernel}/drivers-net/ti/tlan.ko.gz
    rm -rf ${1}/lib/modules/${kernel}/drivers-net/i825xx/znet.ko.gz
  fi;

  for blist_ata in tps65010 htc-pasic3;do
    rm ${1}/lib/modules/${kernel}/drivers-ata/${blist_ata}.ko.gz
  done

  for kmod in drivers/net/mdio.ko.gz drivers/uio/uio.ko.gz drivers/net/mii.ko.gz drivers/net/sungem_phy.ko.gz \
              drivers/net/phy/libphy.ko.gz net/ipv6/ipv6.ko.gz net/unix/unix.ko.gz \
              net/packet/af_packet.ko.gz drivers/ptp drivers/pps/pps_core.ko.gz drivers/dca \
              net/ipv4/inet_lro.ko.gz drivers/misc/eeprom/eeprom_93cx6.ko.gz drivers/base/regmap/regmap-i2c.ko.gz \
              sound/ac97_bus.ko.gz drivers/hwmon drivers/input/input-polldev.ko.gz drivers/char/ipmi \
              drivers/i2c/algos/i2c-algo-bit.ko.gz drivers/net/vxlan.ko.gz lib/lz4/lz4_compress.ko.gz \
              lib/lz4/lz4hc_compress.ko.gz net/bridge/bridge.ko.gz net/802/stp.ko.gz net/llc/llc.ko.gz \
              net/ipv4/udp_tunnel.ko.gz net/ipv6/ip6_udp_tunnel.ko.gz drivers/net/phy/fixed_phy.ko.gz;do

   if [ -f ${2}lib/modules/${kernel}/kernel/${kmod} ];then
     cp ${2}lib/modules/${kernel}/kernel/${kmod} ${1}/lib/modules/${kernel}/drivers
    elif [ -d ${2}lib/modules/${kernel}/kernel/${kmod} ];then
     cp -r ${2}lib/modules/${kernel}/kernel/${kmod} ${1}/lib/modules/${kernel}/drivers
   fi;
  done;

  for nonata in ata_generic.ko.gz pata_legacy.ko.gz ahci_platform.ko.gz pata_acpi.ko.gz libahci.ko.gz;do
    if [ -f ${1}/lib/modules/${kernel}/drivers-ata/${nonata} ];then
      mv ${1}/lib/modules/${kernel}/drivers-ata/${nonata} ${1}/lib/modules/${kernel}/drivers
    fi;
  done;

  for kmod in kernel/fs/fscache/fscache.ko.gz kernel/net/sunrpc/sunrpc.ko.gz kernel/fs/lockd/lockd.ko.gz \
              kernel/net/sunrpc/auth_gss/auth_rpcgss.ko.gz kernel/fs/nfs_common/nfs_acl.ko.gz \
              /kernel/fs/nfs/nfs.ko.gz kernel/fs/nfs_common/grace.ko.gz;do
   if [ -f ${2}lib/modules/${kernel}/${kmod} ];then
     cp ${2}lib/modules/${kernel}/${kmod} ${1}/lib/modules/${kernel}/nfs
    elif [ -d ${2}lib/modules/${kernel}/${kmod} ];then
     cp -r ${2}lib/modules/${kernel}/${kmod} ${1}/lib/modules/${kernel}/nfs
   fi;
  done;

  for kmod in block/loop.ko.gz base/firmware_class.ko.gz pcmcia mmc/core \
           mmc/card misc/cb710 misc/tifm_core.ko.gz cdrom/cdrom.ko.gz ssb \
           usb/host md/ usb/wusbcore uwb usb/misc/ftdi-elan.ko.gz connector/cn.ko.gz \
           hid/hid.ko.gz hid/usbhid hid/hid-generic.ko.gz bcma/bcma.ko.gz;do
   if [ -f ${2}lib/modules/${kernel}/kernel/drivers/${kmod} ];then
     cp ${2}lib/modules/${kernel}/kernel/drivers/${kmod} ${1}/lib/modules/${kernel}/drivers
    elif [ -d ${2}lib/modules/${kernel}/kernel/drivers/${kmod} ];then
     cp -r ${2}lib/modules/${kernel}/kernel/drivers/${kmod} ${1}/lib/modules/${kernel}/drivers
   fi;
  done;

  for kmod in isofs/isofs.ko.gz nls/nls_iso8859-1.ko.gz ext3 ext4 jbd jbd2 squashfs fat vfat nls/nls_cp437.ko.gz;do
    if [ -f ${2}lib/modules/${kernel}/kernel/fs/${kmod} ];then
      cp ${2}lib/modules/${kernel}/kernel/fs/${kmod} ${1}/lib/modules/${kernel}/drivers
     elif [ -d ${2}lib/modules/${kernel}/kernel/fs/${kmod} ];then
      cp -r ${2}lib/modules/${kernel}/kernel/fs/${kmod} ${1}/lib/modules/${kernel}/drivers
    fi
  done;

  for klib in zlib_deflate raid6 lzo libcrc32c.ko.gz crc16.ko.gz crc-t10dif.ko.gz \
	crc-itu-t.ko.gz crc7.ko.gz crc-ccitt.ko.gz;do
    if [ -f ${2}lib/modules/${kernel}/kernel/lib/${klib} ];then
      cp ${2}lib/modules/${kernel}/kernel/lib/${klib} ${1}/lib/modules/${kernel}/drivers
     elif [ -d ${2}lib/modules/${kernel}/kernel/lib/${klib} ];then
      cp -r ${2}lib/modules/${kernel}/kernel/lib/${klib} ${1}/lib/modules/${kernel}/drivers
    fi;
  done;

  for scard in scsi_wait_scan scsi_mod scsi_tgt sd_mod sr_mod libsas \
            scsi_transport_iscsi scsi_transport_fc scsi_transport_sas \
            scsi_transport_spi device_handler cxgbi/libcxgbi megaraid/megaraid_mm \
            libiscsi libiscsi_tcp scsi_transport_iscsi fcoe osd libfc;do
    if [ -f ${2}lib/modules/${kernel}/kernel/drivers/scsi/${scard}.ko.gz ];then
      cp ${2}lib/modules/${kernel}/kernel/drivers/scsi/${scard}.ko.gz ${1}/lib/modules/${kernel}/drivers
     elif [ -d ${2}lib/modules/${kernel}/kernel/drivers/scsi/${scard} ];then
      cp -r ${2}lib/modules/${kernel}/kernel/drivers/scsi/${scard} ${1}/lib/modules/${kernel}/drivers
    fi;
  done
  if [ -d ${2}lib/modules/${kernel}/kernel/crypto ];then
    cp -r ${2}lib/modules/${kernel}/kernel/crypto ${1}/lib/modules/${kernel}/
  fi;
}

initrd_init() {
  for tld in bin dev etc isofs media lib proc sbin sys sysroot var;do
    if [ ! -d ${1}/${tld} ];then
      mkdir ${1}/${tld}
    fi;
  done

  if [ ! -d ${1}/var/lock/lvm ];then
    mkdir -p ${1}/var/lock/lvm
  fi;
  if [ ! -d ${1}/etc/lvm ];then
    mkdir ${1}/etc/lvm
  fi;
  for lvmdir in archive backup cache;do
    if [ ! -d ${1}/etc/lvm/${lvmdir} ];then
      mkdir ${1}/etc/lvm/${lvmdir}
    fi;
  done;

  (cp ${2}/etc/lvm/lvm.conf ${1}/etc/lvm/
  cp ${2}/usr/sbin/lvm.static ${1}/sbin/lvm
  if [ -x ${2}/sbin/modprobe.static ];then
    cp ${2}/sbin/modprobe.static ${1}/sbin/modprobe
   else
    cp ${2}/usr/bin/modprobe.static ${1}/sbin/modprobe
  fi
  if [ -x ${2}/sbin/mdadm ];then
    cp ${2}/sbin/mdadm ${1}/sbin/
  fi;
  if [ -x ${2}/bin/mount.static ];then
    cp ${2}/bin/mount.static ${1}/bin/mount
   else
    cp ${2}/sbin/mount.static ${1}/bin/mount
  fi;
  if [ -x ${2}/sbin/mount.aufs ];then
    cp ${2}/sbin/mount.aufs ${1}/sbin/
  fi;
  cp ${2}/sbin/mount.nfs.static ${1}/sbin/mount.nfs
  mkdir -p ${1}/usr/share/udhcpc/
  cp ${2}/usr/share/udhcpc/distrotech-nfs.script ${1}/usr/share/udhcpc/default.script
  ln -s -r ${1}/proc/mounts ${1}/etc/mtab
  ln -s -r ${1}/sbin/lvm ${1}/sbin/vgchange
  ln -s -r ${1}/sbin/lvm ${1}/sbin/vgscan
  ln -s -r ${1}/sbin/lvm ${1}/sbin/vgmknodes
  ln -s -r ${1}/linuxrc ${1}/sbin/init
  ln -s -r ${1}/sbin/mount.nfs ${1}/sbin/mount.nfs4
  if [ -e ${2}/boot/busybox.tgz ];then
    tar -C ${1} -xf ${2}/boot/busybox.tgz
  fi;
  touch ${1}/etc/fstab) 2>/dev/null

  dst=${1}
  shift
  src=${1}
  shift
  while [ "${1}" ];do
    init_rd_drivers ${dst} ${src} ${1}
    shift
  done
}

init_rd_drivers_scsi() {
  cd ${2}lib/modules/${3}
  for ADAPTER in `lspci -nm |awk -F\" '$2 == "Class 0100" || $2 == "Class 0101" || $2 == "Class 0102" || $2 == "Class 0103" || $2 == "Class 0104" || $2 == "Class 0106" || $2 == "Class 0107" || $2 == "Class 0180" {printf "grep -E \"%s.*%s\" modules.pcimap\n",$4,$6}' |sh |awk '{print $1}'`${EXTRA_DEV};do 
    if [ "$ADAPTER" == "sym53c8xx" ];then
      ADAPTER="sym53c8xx_2/sym53c8xx";
    fi;
    if [ "$ADAPTER" == "aic79xx" ];then
      ADAPTER="aic7xxx/aic79xx";
    fi;
    if [ "$ADAPTER" == "megaraid_sas" ] || [ "$ADAPTER" == "megaraid_mbox" ];then
      ADAPTER="megaraid/${ADAPTER}";
    fi;
    if [ "$ADAPTER" == "cxgb4i" ] || [ "$ADAPTER" = "cxgb3i" ];then
      ADAPTER="cxgbi/${ADAPTER}/${ADAPTER}";
    fi;

    if [ -e ${2}lib/modules/${3}/kernel/drivers/scsi/$ADAPTER.ko.gz ];then
      cp ${2}lib/modules/${3}/kernel/drivers/scsi/$ADAPTER.ko.gz ${1}/lib/modules/${3}/drivers-scsi
     elif [ -d ${2}lib/modules/${3}/kernel/drivers/scsi/$ADAPTER ];then
      cp -r ${2}lib/modules/${3}/kernel/drivers/scsi/$ADAPTER/* ${1}/lib/modules/${3}/drivers-scsi
     elif [ -e ${2}lib/modules/${3}/kernel/drivers/message/fusion/$ADAPTER.ko.gz ];then
      cp -r ${2}lib/modules/${3}/kernel/drivers/message/fusion/* ${1}/lib/modules/${3}/drivers-scsi
     elif [ -e ${2}lib/modules/${3}/kernel/drivers/message/i2o/$ADAPTER.ko.gz ];then
      cp -r ${2}lib/modules/${3}/kernel/drivers/message/i2o/* ${1}/lib/modules/${3}/drivers-scsi
    fi;
  done
}

initrd_config() {
  ROOTDEV=`grub-probe -t fs_uuid ${2} 2>/dev/null`
  if [ ! "${ROOTDEV}" ] && [ -e /dev/lvm/root ];then
    ROOTDEV=`blkid -s UUID -o value /dev/lvm/root`
  fi;
  cat <<_EOF_
#!/bin/ash

echo "Distrotech Linux Starting"

/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t devtmpfs none /dev

for copt in \`cat /proc/cmdline\`;do
  if [ "\${copt#${KSUF}_bash=}" == "\${copt}" ];then
    ${KSUF}_bash="1";
  fi;
done

_EOF_

  for driver in `ls ${1}/lib/modules/${3}/drivers-scsi/ |cut -d. -f1`;do
    echo "modprobe ${driver}"
  done;

  for driver in `ls ${1}/lib/modules/${3}/drivers-ata/ |cut -d. -f1`;do
    echo "modprobe ${driver}"
  done;

  cat <<_EOF_

modprobe pata_acpi
modprobe ata_generic
modprobe ehci_hcd
modprobe uhci_hcd
modprobe ohci_hcd
modprobe bcma-hcd
modprobe isp116x-hcd
modprobe isp1362-hcd
modprobe oxu210hp-hcd
modprobe r8a66597-hcd
modprobe sl811-hcd
modprobe ssb-hcd
modprobe u132-hcd
modprobe xhci-hcd
_EOF_

  for driver in `ls ${1}/lib/modules/${3}/drivers-usb |cut -d. -f1`;do
    echo "modprobe ${driver}"
  done;

  cat <<_EOF_
modprobe sd_mod

modprobe loop
modprobe dm-mod
modprobe usbhid
modprobe hid-generic

_EOF_

  if [ "$USBSLEEP" ];then
    echo "sleep ${USBSLEEP}"
  fi;

#  /sbin/dmraid -c -sa -i > /dev/null 2>&1
#  if [ $? == 0 ];then
#    echo "/sbin/dmraid -ay -i"
#  fi;

  if [ -e /etc/mdadm.conf ];then
    cat <<_EOF_
/sbin/mdadm -Ebsc part > /etc/mdadm.conf
/sbin/mdadm -As
_EOF_
  fi;

  if [ "${LOOP_FILE}" ] && [ "${LOOP_DEV}" ];then
    cat << _EOF_
/bin/mount -n -o ro -t `blkid ${LOOP_DEV} -s TYPE -o value` -U `grub-probe -t fs_uuid -d ${LOOP_DEV}` /isofs
/bin/mount -t devtmpfs none /isofs/dev
/bin/mount -t proc none /isofs/proc
/bin/mount -t sysfs none /isofs/sys
/sbin/pivot_root /isofs /isofs/media
/sbin/fsck -TCAa
/bin/mount / -o remount,rw
/sbin/losetup /dev/loop0 ${LOOP_FILE}
umount /proc
umount /dev
umount /sys
/sbin/pivot_root /media /media/isofs

_EOF_
  fi;

  if [ -e /etc/initrd.local ];then
    echo
    cat /etc/initrd.local
    echo
  fi;

cat <<_EOF_
modprobe ext4
sleep 5
vgchange -a y --sysinit lvm
mount -t ramfs none /var/lock/lvm
vgmknodes
umount /var/lock/lvm
/bin/mount -o ro -t ext4 -U ${ROOTDEV} /sysroot
echo 0x0100 > /proc/sys/kernel/real-root-dev

/sbin/pivot_root /sysroot /sysroot/initrd
mount -t proc none /proc
mount -t sysfs none /sys
umount /initrd/proc
umount /initrd/sys
umount /initrd/dev

_EOF_
}

mkbootimg_cfg() {
  cat << EOF
#!/bin/ash

EOF

for driver in `ls ${1}/lib/modules/${2}/drivers-ata |cut -d. -f1`;do
  echo "modprobe ${driver}"
done;

  cat << EOF

modprobe pata_acpi
modprobe ata_generic
modprobe ehci_hcd
modprobe uhci_hcd
modprobe ohci_hcd
modprobe bcma-hcd
modprobe isp116x-hcd
modprobe isp1362-hcd
modprobe oxu210hp-hcd
modprobe r8a66597-hcd
modprobe sl811-hcd
modprobe ssb-hcd
modprobe u132-hcd
modprobe xhci-hcd
EOF

for driver in `ls ${1}/lib/modules/${2}/drivers-usb |cut -d. -f1`;do
  echo "modprobe ${driver}"
done;

  cat << EOF
modprobe sd_mod
modprobe sr_mod
modprobe cdrom
modprobe loop
modprobe dm-mod
modprobe usbhid
modprobe hid-generic
modprobe ext4
EOF

  if [ "${3}" == "dvd" ];then
    cat << EOF
sleep 5
/bin/mount -n -o ro -t iso9660 -L DISTROTECH_INSTALL /isofs
/sbin/losetup /dev/loop0 /isofs/flash.hdd

EOF
   elif [ "${3}" == "nfs" ];then
    for netint in `ls ${1}/lib/modules/${2}/drivers-net/*.ko.gz ${1}/lib/modules/${2}/drivers-net/*/*.ko.gz ${1}/lib/modules/${2}/drivers-net/*/*/*.ko.gz`;do
      echo modprobe `basename ${netint} |cut -d. -f1`;
    done
    cat << EOF
modprobe unix
modprobe ipv6
modprobe af_packet

sleep 5

/bin/ip link set dev eth0 down
/bin/ip link set dev eth0 name ethA
/sbin/udhcpc -i ethA -q
echo 0x0100 > /proc/sys/kernel/real-root-dev

/sbin/pivot_root /sysroot /sysroot/initrd

mount -M /initrd/proc /proc
mount -M /initrd/sys /sys
mount -M /initrd/dev /dev

EOF
   elif [ "${3}" == "rootfs" ];then
    cat << EOF
sleep 10
vgchange -a y --sysinit
mount -t ramfs none /var/lock/lvm
vgmknodes
umount /var/lock/lvm
/bin/mount -n -o ro \${rootfs} /sysroot
echo 0x0100 > /proc/sys/kernel/real-root-dev

/sbin/pivot_root /sysroot /sysroot/initrd

mount -M /initrd/proc /proc
mount -M /initrd/sys /sys
mount -M /initrd/dev /dev

EOF
   elif [ "${3}" == "squashfs" ];then
    cat << EOF
modprobe vfat
modprobe nls-cp437
modprobe nls-iso8859-1
modprobe squashfs

sleep 4

mke2fs -q /dev/ram1 >/dev/null 2>&1
mount -n /dev/ram1 /media
mkdir /media/isofs
mkdir /media/install
mkdir /media/installer
mkdir /media/user

mount -n -o ro -L DTS_INSTALL /media/isofs
losetup /dev/loop0 /media/isofs/\${squashimg}

mount -n -o ro /dev/loop0 /media/installer
mount -t tmpfs tmprw /media/user

mount -n -t aufs -o br:/media/user=rw+moo:/media/installer=rr none /sysroot >/dev/null 2>&1

mount -M /media /sysroot/media

echo 0x0100 > /proc/sys/kernel/real-root-dev

pivot_root /sysroot /sysroot/initrd

mount -M /initrd/proc /proc
mount -M /initrd/sys /sys
mount -M /initrd/dev /dev
mount -t tmpfs rundir /run

EOF
   elif [ "${3}" == "buildroot" ];then
    cat << EOF
modprobe vfat
modprobe nls-cp437
modprobe nls-iso8859-1
modprobe squashfs

sleep 4

mke2fs -q /dev/ram1 >/dev/null 2>&1
mount -n /dev/ram1 /media
mkdir /media/isofs
mkdir /media/install
mkdir /media/installer
mkdir /media/buildroot
mkdir /media/user

mount -o ro -L DTS_INSTALL /media/isofs
losetup /dev/loop0 /media/isofs/\${squashimg}
losetup /dev/loop1 /media/isofs/\${buildimg}

mount -o ro /dev/loop0 /media/installer
mount -o ro /dev/loop1 /media/buildroot
mount -t tmpfs tmprw /media/user

mount -t aufs -o br:/media/user=rw+moo:/media/buildroot=rr:/media/installer=rr build /sysroot > /dev/null 2>&1

mount -M /media /sysroot/media

echo 0x0100 > /proc/sys/kernel/real-root-dev

pivot_root /sysroot /sysroot/initrd

mount -M /initrd/proc /proc
mount -M /initrd/sys /sys
mount -M /initrd/dev /dev
mount -t tmpfs rundir /run

EOF
   else
    cat << EOF
sleep 10
vgchange -a y --sysinit
mount -t ramfs none /var/lock/lvm
vgmknodes
umount /var/lock/lvm
/bin/mount -n -o ro -t ext4 -L INSTALL /sysroot
echo 0x0100 > /proc/sys/kernel/real-root-dev

/sbin/pivot_root /sysroot /sysroot/initrd

mount -M /initrd/proc /proc
mount -M /initrd/sys /sys
mount -M /initrd/dev /dev

EOF
  fi;
}

mkbootimg() {
  initrd_init ${1} ${2} ${3}

  if [ ! -d ${1}/etc/modprobe.d ];then
    mkdir ${1}/etc/modprobe.d
  fi;
  (cat << EOF
options loop meax_part=63
options sg allow_dio=1
EOF
) > ${1}/etc/modprobe.d/modprobe.conf

  (cat << EOF
#!/bin/ash

echo "Distrotech Linux Starting"

/bin/mount -t devtmpfs none /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

for copt in \`cat /proc/cmdline\`;do
  if [ "\${copt#${KSUF}_opt=}" != "\${copt}" ];then
    ${KSUF}_opt=\${copt#${KSUF}_opt=}
  fi;
  if [ "\${copt#root=}" != "\${copt}" ];then
    rootfs=\${copt#root=}
    export rootfs
  fi;
  if [ "\${copt#squashimg=}" != "\${copt}" ];then
    squashimg=\${copt#squashimg=}
    export squashimg
  fi;
  if [ "\${copt#buildimg=}" != "\${copt}" ];then
    buildimg=\${copt#buildimg=}
    export buildimg
  fi;
done

case \$${KSUF}_opt in
  dvd)exec /sbin/linuxrc.dvd;;
  nfs)exec /sbin/linuxrc.nfs;;
  install)exec /sbin/linuxrc.install;;
  squashfs)exec /sbin/linuxrc.squashfs;;
  buildroot)exec /sbin/linuxrc.buildroot;;
esac

exec /sbin/linuxrc.rootfs

EOF
) > ${1}/linuxrc
  chmod 750 ${1}/linuxrc

  mkbootimg_cfg ${1} ${3} > ${1}/sbin/linuxrc.install
  mkbootimg_cfg ${1} ${3} dvd > ${1}/sbin/linuxrc.dvd
  mkbootimg_cfg ${1} ${3} nfs > ${1}/sbin/linuxrc.nfs
  mkbootimg_cfg ${1} ${3} rootfs > ${1}/sbin/linuxrc.rootfs
  mkbootimg_cfg ${1} ${3} squashfs > ${1}/sbin/linuxrc.squashfs
  mkbootimg_cfg ${1} ${3} buildroot > ${1}/sbin/linuxrc.buildroot

  chmod 750 ${1}/sbin/linuxrc*
  ${2}/sbin/depmod -b ${1} -aeF ${2}/boot/System.map-${3} ${3}
}

mk_initrd() {
  if [ -d /dev/loop ];then
    rm -rf /dev/loop
  fi;

  if [ -h /boot/boot ];then
    rm /boot/boot
  fi;

  if [ ! -d ${2}/lib/modules/${3} ];then
    echo "No Kernel Directory ${2}/lib/modules/${3}"
    return 255
  fi;

  if [ "$EXTRA_DEV" ];then
    EXTRA_DEV=" ${EXTRA_DEV}"
  fi;

  LOOP=`losetup -f`
  if [ ! "${LOOP}" ] || [ ! -e "${LOOP}" ];then
    return 255
  fi;

  TINIT=/tmp/initrd_$$${RANDOM}
  while [ -e ${TINIT} ];do
    TINIT=/tmp/initrd_$$${RANDOM}
  done;

  (dd if=/dev/zero of=${TINIT} bs=1M count=24
  mkfs.ext2 -F -L initrd -i 1024 ${TINIT}
  losetup ${LOOP} ${TINIT}
  mount ${LOOP} ${1}) >/dev/null 2>&1

  initrd_init ${1} ${2} ${3}
  cp -r ${2}/etc/modprobe.d ${1}/etc/

  ${2}/sbin/depmod -a -F ${2}/boot/System.map-${3} -b ${2} ${3}
  (init_rd_drivers_scsi ${1} ${2} ${3})
  ${2}/sbin/depmod -a -e -F ${2}/boot/System.map-${3} -b ${1} ${3}

  initrd_config ${1} ${2} ${3} > ${1}/linuxrc
  chmod 750 ${1}/linuxrc

  umount ${1}
  losetup -d ${LOOP}

  (e2fsck -Dfy ${TINIT}
  dd if=${TINIT} bs=1k |gzip -c9 > ${2}/boot/initrd-${3}
  rm ${TINIT} ${2}/boot/initrd.img ${2}/boot/vmlinuz ${2}/boot/System.map > /dev/null 2>&1

  ln -s vmlinuz-${3} ${2}/boot/vmlinuz
  ln -s System.map-${3} ${2}/boot/System.map
  ln -s initrd-${3} ${2}/boot/initrd.img) > /dev/null 2>&1

  return 0
}

if [ "${1}" == "" ];then
  if [ -e /etc/netsentry-version ];then
    eval `cat /etc/netsentry-version`
   else
    echo "No Config File"
    exit -1
  fi;

  if [ -d /lib/modules/${KERNEL}-${KSUF} ];then
    mk_initrd /mnt/initrd / ${KERNEL}-${KSUF}
   else
    mk_initrd /mnt/initrd / ${KERNEL}
  fi;
  grub-mkconfig -o /boot/grub/grub.cfg
 elif [ "${1}" == "bootimg" ];then
  shift
  TMPDIR=$(mktemp -d /tmp/bootinitrd-XXXXXXXX)
  if [ ! "${TMPDIR}" ] || [ ! -d ${TMPDIR} ];then
    exit 1;
  fi

  INITRD=$(mktemp  /tmp/bootinitrd-XXXXXXXX)
  if [ ! "${INITRD}" ] || [ ! -e ${INITRD} ];then
    exit 1;
  fi

  ILOOP=`losetup -f`
  if [ ! "${ILOOP}" ] || [ ! -e "${ILOOP}" ];then
    exit 1;
  fi;

  (dd if=/dev/zero of=${INITRD} bs=1M count=24
  losetup ${ILOOP} ${INITRD}
  mkfs.ext2 -F -L initrd -i 1024 ${INITRD}
  mount ${ILOOP} ${TMPDIR}/) > /dev/null 2>&1

  mkbootimg ${TMPDIR} ${2} ${3}

  sleep 2
  umount ${TMPDIR}

  e2fsck -Dfy ${ILOOP} > /dev/null 2>&1

  sleep 2
  losetup -d ${ILOOP}

  (dd if=${INITRD} |gzip -c9 > ${1}) > /dev/null 2>&1

  rm -rf ${TMPDIR} ${INITRD}
fi;
