#!/bin/bash

MPNT=/mnt

(vgscan
vgchange -a y) > /dev/null

if [ "${1}" ];then
  root=${1}
 elif [ -e /dev/lvm/root ];then
  root=/dev/lvm/root
 else
  root=`findfs LABEL=root 2>/dev/null`
fi;

if [ ! "${root}" ];then
  echo "No root device specified"
  exit -1
fi;

mount ${root} ${MPNT} -o ro
if [ $? != 0 ];then
  echo "Mount failed"
  exit -1
fi;

for bind in dev proc sys;do
  mount --bind /${bind} ${MPNT}/${bind}
done;

chroot ${MPNT} fsck -TCAa
RES=$?
if (( ${RES} >= 2 )) && (( ${RES} != 32 ));then
  for bind in dev proc sys;do
    umount ${MPNT}/${bind}
  done;
  umount ${MPNT}
  echo "FILE SYSTEM ERROR"
  if [ ${RES} == 2 ];then
    echo "REBOOT REQUIRED"
  fi;
  exit ${RES}
fi;

mount ${MPNT} -o remount,rw
rm ${MPNT}/etc/mtab
touch ${MPNT}/etc/mtab
chroot ${MPNT} mount -f /
chroot ${MPNT} swapon -a
chroot ${MPNT} mount -a
if [ -e ${MPNT}/etc/HOSTNAME ];then
  cp ${MPNT}/etc/hosts ${MPNT}/etc/resolv.conf /etc
  hostname -F ${MPNT}/etc/HOSTNAME
fi;

if [ "`findfs LABEL=UPGRADE`" ];then
  mount -L UPGRADE -o ro ${MPNT}/mnt/update
  if [ $? == 0 ];then
    mount --bind / ${MPNT}/mnt/update/mnt/dev -o ro
    if [ -e ${MPNT}/var/run/rsyncd.pid ];then
      rm ${MPNT}/var/run/rsyncd.pid
    fi;
    cp -p /usr/sbin/vbox_upgrade /usr/sbin/flashutil /${MPNT}/usr/sbin
    cp -pr /etc/rsyncd* ${MPNT}/etc
    chroot ${MPNT} rsync --daemon --config /etc/rsyncd-update.conf
  fi;
fi;

#chroot ${MPNT}
#while [ "`pidof rsync`" ];do
#  killall rsync
#  sleep 2
#done;
#awk '/.* \/mnt/ {printf "%s:%s\n",length($2),$2}' /proc/mounts |sort -nr |awk -F: '{printf "umount %s\n",$2}' |sh
