#!/bin/bash

ROOTPW=`cat /etc/ldap.secret`

if [ -e "/etc/samba/smb.conf" ];then
  /usr/bin/smbpasswd -w ${ROOTPW} > /dev/null 2>&1
  (/usr/bin/net idmap secret '*' ${ROOTPW} > /dev/null 2>&1) &
  /usr/sbin/add_domain  SMARTDNS >/dev/null 2>&1
  (cat<<EOF
${ROOTPW}
${ROOTPW}
EOF
) | smbpasswd -sa admin &
fi;

touch /etc/shadow.new
chmod 400 /etc/shadow.new

CRYPT=$(slappasswd -c '$6$%.12s' -T /etc/ldap.secret |cut -c8-)
SECS=$(date +%s)
DAYS=$(echo "${SECS} / 86400" |bc)

(echo "root:${CRYPT}:${DAYS}::99999:0:0:65535:"
echo "admin:${CRYPT}:${DAYS}::99999:0:0:65535:"
grep -vE "^(root|admin):" /etc/shadow) > /etc/shadow.new
mv /etc/shadow.new /etc/shadow
