#!/bin/bash

if [ -e /var/spool/apache/htdocs/ns/config/ldap.newsecret ];then
  ROOTPW=`cat /var/spool/apache/htdocs/ns/config/ldap.newsecret`
  rm /var/spool/apache/htdocs/ns/config/ldap.newsecret
  touch /etc/ldap.secret
  chmod 400 /etc/ldap.secret
  chown root.root /etc/ldap.secret
  echo "${ROOTPW}" > /etc/ldap.secret
 else
  ROOTPW=`cat /etc/ldap.secret`
fi;

if [ -e "/etc/samba/smb.conf" ];then
  /usr/bin/smbpasswd -w ${ROOTPW} > /dev/null 2>&1
  (/usr/bin/net idmap secret '*' ${ROOTPW} > /dev/null 2>&1) &
  /usr/sbin/add_domain  SMARTDNS >/dev/null 2>&1
  (cat<<EOF
${ROOTPW}
${ROOTPW}
EOF
) | smbpasswd -sa admin &
fi;

touch /etc/shadow.new
chmod 400 /etc/shadow.new

(getent shadow |grep -E "^admin:"  |tail -1 |sed -e "s/admin\(:.*\)/root\1/"
grep -vE "^root:" /etc/shadow) > /etc/shadow.new
mv /etc/shadow.new /etc/shadow
