<%
$sessid=session_id();
if ($sessid == "") {
  if (!isset($_GET['sesname'])) {
    $_GET['sesname']="server_admin";
  }
  ob_start('ob_gzhandler');
  include "/var/spool/apache/htdocs/session.inc";
  session_name($_GET['sesname']);
  session_set_cookie_params(288800);
  session_start();
}
$disppage=$_SESSION['disppage'];
%>
var HINTS_CFG = {
	'top'        : 5, // a vertical offset of a hint from mouse pointer
	'left'       : 5, // a horizontal offset of a hint from mouse pointer
	'css'        : 'hintsClass', // a style class name for all hints, TD object
	'show_delay' : 1000, // a delay between object mouseover and hint appearing
	'hide_delay' : 5000, // a delay between hint appearing and hint hiding
	'wise'       : true,
	'follow'     : true,
	'z-index'    : 0 // a z-index for all hint layers
},

HINTS_ITEMS = {
  <%if (($disppage == "cdr/mkuser.php") || ($disppage == "reception/mkuser.php")){%>
    'ESS0':gen_hint('<%print _("Select Extension");%>','<%print _("Select the extension from the list by name or type in the extension number bellow to add or edit the extension");%>'),
    'ESS1':gen_hint('<%print _("Enter Extension");%>','<%print _("If you know the extension number or want to create new one enter the number here.Please note you can only edit or add numbers to your prefix when entering the number select the prefix from the drop down list and enter only the last 2 digits of the extension.If there is no configured prefix you will be able to type in the prefix (only on new systems)");%>'),
    'ES1':gen_hint('<%print _("Fullname");%>','<%print _("Enter the users fullname.") . "<BR>" . _("This is used for caller ID and informational purposes.");%>'),
    'ES2':gen_hint('<%print _("Email Address");%>','<%print _("Enter the users email address.") . "<BR>" . _("This address will be the address used to send voice mail attachments and FAX messages.");%>'),
    'ES3':gen_hint('<%print _("Immeadiate Call Forward");%>','<%print _("When set any call for this extension will be immeadiately forwarded to the number entered here. Please note this setting will not ring the phone and bypasses voicemail.") . "<BR>" . _("There is no default setting.");%>'),
    'ES4':gen_hint('<%print _("Call Forward When Busy/DND");%>','<%print _("When set any call for this extension will be forwarded to the number entered here when the extension is logged off or turned off or call waiting is disabled.if DND (Do Not Disturb) is set the phone is concidered busy. Please note this setting will not ring the phone and bypasses voicemail.") . "<BR>" . _("By default calls will be procesed by voicemail or bounced to reception if voice mail is disabled");%>'),
    'ES5':gen_hint('<%print _("Call Forward On Ring Timeout (No Answer)");%>','<%print _("When set any call for this extension will be forwarded to the number entered here when the extension is ignored and a call rings longer than the ring timeout. Please note this setting bypasses voicemail.") . "<BR>" . _("By default calls will be procesed by voicemail or bounced to reception if voice mail is disabled");%>'),
    'ES6':gen_hint('<%print _("Call Forward On FAX");%>','<%print _("When a fax signal is detected the call will be rerouted to the number set here") . "<BR>" . _("By default a incoming fax will go to the default FAX terminal if set and the extension is not enabled for FAX reception.If there is no default terminal set the user will recive the fax on the email address set in the extension if FAX to mail is enabled,if there is no email address set or FAX to mail is not enabled the default fax handler mail box will be used.");%>'),
    'ES7':gen_hint('<%print _("Ring Timeout");%>','<%print _("This sets the maximum time a phone can ring in seconds before been treated as not answered.") . "<BR>" . _("When the extension is a agent in a call queue this setting is ignored and the call queue setting superceeds it for calls coming in to the queue.");%>'),
    'ES8':gen_hint('<%print _("Call Waiting");%>','<%print _("When enabled and a call is recived when the extension is in use a call waiting tone will be played to the user and the call in progress can be placed on hold and the incoming call atteneded to.The user will be able to switch from one call to another.") . "<BR>" . _("Some devices allow 3 way conference calling allowing all 3 parties to be connected simultaneously.");%>'),
    'ES9':gen_hint('<%print _("Do Not Disturb (DND)");%>','<%print _("When enabled the phone will be concidered as busy and all calls will be handled as if it was busy.") . "<BR>" . _("Please note this does not set your status to unreachable as if the phone is turned off.");%>'),
    'ES10':gen_hint('<%print _("Caller Group");%>','<%print _("Enter the group(s) the extension belongs to seperating each group with a comma.Setting this will allow users whose pickup group matches this call group will be able to pickup the ringing line.") . "<BR>" . _("There are 32 groups from 0 to 31.");%>'),
    'ES11':gen_hint('<%print _("Pickup Group");%>','<%print _("Enter the group(s) the extension is authorised to pickup ringing calls for.") . "<BR>" . _("The same rules apply as for the pickup group above");%>'),
    'ES12':gen_hint('<%print _("Extension Permision");%>','<%print _("This is the permision to make calls from this extension there is a higher level where the user will have to enter a password.") . "<BR>";%>'),
    'ES13':gen_hint('<%print _("Authentication Permision");%>','<%print _("When set to a higher level than the extension permision a user can make a call on this extension to this level after entering the password when prompted");%>'),
    'ES14':gen_hint('<%print _("Password");%>','<%print _("Enter the password for this extension and voicemail box.");%>'),
    'ES15':gen_hint('<%print _("Password Confirmation");%>','<%print _("As the password is not shown on the page you need to confirm it incase there is a mistake");%>'),
    'ES16':gen_hint('<%print _("Roaming Password");%>','<%print _("This password is used when making a call from another extension to show up on this exetension.") . "<BR>" . _("To make a roaming call prefix the number with *6 from any extension.");%>'),
    'ES17':gen_hint('<%print _("Password Confirmation");%>','<%print _("As the password is not shown on the page you need to confirm it incase there is a mistake");%>'),
    'ES18':gen_hint('<%print _("CLI Displayed On Trunk Calls");%>','<%print _("This is the number that will be requested to be displayed to the called party.As the number is requested it needs to be authorised by the carrier and as such will most likely need to be in a range of assigned numbers.Not all connections support this curently ISDN and some VOIP connections only.");%>'),
    'ES19':gen_hint('<%print _("Call Recording");%>','<%print _("If selected all calls to and from this extension will be recorded , please note calls originating in a queue will be recorded based on the setting of the queue.");%>'),
    'ES20':gen_hint('<%print _("Disable Voice Mail");%>','<%print _("If selected when this extension is busy or there is no answer a call will not be directed to voice mail but be diverted to reception.") . "<BR>" . _("Please note that setting a call forward on busy or no answer overrides this setting.");%>'),
    'ES21':gen_hint('<%print _("Lock Extension");%>','<%print _("If this extension is locked the extension password will be required to make a call");%>'),
    'ES22':gen_hint('<%print _("Enable Fax To Mail");%>','<%print _("If selected and call forward on fax is not selected a incoming FAX will be directed to the email address set for the extension");%>'),
    'ES23':gen_hint('<%print _("Early Fax Detect");%>','<%print _("If enabled a call to this line will be answered as soon as it rings to allow for the detaction of FAX tones.") . "<BR>" . _("If it is not enabled a fax can only be detected when the call is picked up or gets ansered by voicemail.");%>'),
    'ES24':gen_hint('<%print _("Snom/Linksys Hardware Address");%>','<%print _("Every device on the network has a hardware address or MAC (Media Access Control) address,this address is used by the Snom phone\'s and Linksys adapters to obtain configuration information from the server.") . "<BR>" . _("This address can be found on the device and looks like a serial number and consits of 12 digits consisting of the numbers 0-9 and letters A-F.");%>'),
    'ES25':gen_hint('<%print _("Registration Server");%>','<%print _("It may sometimes be needed to register the phone with a IP other than the one detected by the server.") . "<BR>" . _("A use for this facility is when a phone is taken home and used at home or at work you will set the server to be a SRV record pointing to both the internal and external addreses.");%>'),
    'ES26':gen_hint('<%print _("Lock Snom Settings");%>','<%print _("A Snom phone has the ability to prevent users manipulating priviledged settings,by enableing this option this featire will be activated");%>'),
    'ES27':gen_hint('<%print _("Snom Keypad Keys");%>','<%print _("A Snom 320/360 phone has 12 programable function keys and can be extended with 42 keys by adding the keypad extender,by pressing on the button a window will be popped up that will allow you to program these keys.") . "<BR>" . _("To program the button click on it (middle colum) and enter the extension you wish to program on that button.") . "<P><B>" . _("Special Options") . "</B><P><UL><LI>" . _("0 - Delete Programed Button") . "</LI><LI>" . _("1 - Program As A Incoming Line") . "</LI><LI>" . _("700 - Call Park") . "</LI><LI>" . _("701-749 - Park Pickup") . "</LI><LI>" . _("900-999 - Conference Rooms") . "</LI></UL>";%>'),
    'ES29':gen_hint('<%print _("Console Group");%>','<%print _("The flash operator pannel or web console can be split up into multiple views or groups,select the group or enter a name for a group to be created.");%>'),
    'ES30':gen_hint('<%print _("Number Of Lines Viewable");%>','<%print _("A extension can occupy more than one position on the operator pannel if this is required enter the number of positions here.");%>'),
    'ES31':gen_hint('<%print _("Open CRM Page On Incoming Call");%>','<%print _("When the user is logged onto the operator pannel and and a call comes in it can trigger a web popup for sugar CRM.Basicaly it will attempt to open the CRM page assosiated with the caller id of the call.");%>'),
    'ES32':gen_hint('<%print _("Exclude From Voip Routing");%>','<%print _("If enabled the extension will only use telco connections for trunk calls,this will be required for the transmision of FAX messages that cant be sent over VOIP connections");%>'),
    'ES33':gen_hint('<%print _("IAX Protocol");%>','<%print _("IAX is a protocol used by some devices instead of SIP.");%>'),
    'ES34':gen_hint('<%print _("NAT Handling");%>','<%print _("VOIP devices as a rule do not cope with NAT very well symetric response routing can be used to circumvent this problem.");%>'),
    'ES35':gen_hint('<%print _("DTMF Handling");%>','<%print _("DTMF (Dual Tone Multi Frequency) is a means useing the keypad on the phone to enter data onto automatic atendants.There are 3 ways of transmiting DTMF") . "<UL><LI>" . _("Inband - This is the way it is done in non VOIP telecomunication and cannot be used when there is voice compression on the line.") . "</LI><LI>" . _("SIP Info - A special SIP message is sent containing the DTMF.") . "</LI><LI>" . _("RFC2833 (Standard) - This is the standard for transmision of DTMF with VOIP") . "</LI></UL>";%>'),
    'ES36':gen_hint('<%print _("Relaxed Authentication");%>','<%print _("Some devices are not able to authenticate calls correctly in this case you may chose to ignore parts of the autentication.") . "<UL><LI>" . _("Invite - Dont for authenticate a incoming call") . "</LI><LI>" . _("Port - Allow multiple connections from the same IP") . "</LI></UL>";%>'),
    'ES37':gen_hint('<%print _("Allow Peer To Peer Reinvite");%>','<%print _("Allow the extension to attempt to bypass the server and connect peer to peer.There is no gaurentee this will indeed succeed if it fails the call will not be affected.");%>'),
    'ES38':gen_hint('<%print _("Allow Call Forwarding");%>','<%print _("Allow call forwarding by this device");%>'),
    'ES39':gen_hint('<%print _("Send Nat Keep Alive Packets");%>','<%print _("Send periodic information to the device that will allow connections to be maintained behined NAT connections where the connection would otherwise not be maintained.");%>'),
    'ES40':gen_hint('<%print _("TDM Port (Channel Bank/Analogue Port)");%>','<%print _("If the extension is configured for use on a TDM port enter the port number here.");%>'),
    'ES41':gen_hint('<%print _("Gatekeeper IP Address");%>','<%print _("IP address that will be authorised for H.323 connections for this account");%>'),
    'ES42':gen_hint('<%print _("Recived Prefix");%>','<%print _("All calls coming in for this account from the gatekeeper IP will be prefixed with this prefix.");%>'),
    'ES43':gen_hint('<%print _("Gatekeeper ID");%>','<%print _("The ID of this H.323 Account");%>'),
    'ES44':gen_hint('<%print _("Audio Codec");%>','<%print _("This allows you to select the level of audio compresion that is compatible with the device,it is recomended except for FAX terminals the highest level of compression is used.") . "<P><B>" . _("Codecs in order of compression (highest to lowest)") . "<UL><LI>" . _("G.729") . "</LI><LI>" . _("SPEEX (Not Often Used)") . "</LI><LI>GSM</LI><LI>ILBC</LI><LI>G.726</LI><LI>ALAW</LI><LI>&mu;LAW</LI></UL>";%>'),
    'ES45':gen_hint('<%print _("Video Codec");%>','<%print _("If the device supports video select the supported video codecs");%>'),
    'ES46':gen_hint('<%print _("TDM Port Signaling");%>','<%print _("Select the correct signaling type for this port.");%>'),
    'ES47':gen_hint('<%print _("TDM Port RX Gain");%>','<%print _("Adjust the gain toward the PBX to reduce echo and volume.");%>'),
    'ES48':gen_hint('<%print _("TDM Port TX Gain");%>','<%print _("Adjust the gain from the PBX to reduce echo and volume.");%>'),
    'ES49':gen_hint('<%print _("H.323 Phone");%>','<%print _("All calls to this extension use H.323.The H.323 Settings Need To Be Configured Bellow.");%>'),
    'ES50':gen_hint('<%print _("H.323 Neighbor");%>','<%print _("This connection is trusted and part of the local H.323 for making and reciving calls from and to providers and other neighbors.") . "<P><B>" . _("This is security risk if set incorectly.");%>'),
  <%} else if (($disppage == "ldap/addsnom.php") || ($disppage == "ldap/userinfo.php") || ($disppage == "ldap/vzone.php") || ($disppage == "ldap/trustinfo.php") || ($disppage == "ldap/snominfo.php") || ($disppage == "ldap/mserverinfo.php") || ($disppage == "auth/sslcreate.php") || ($disppage == "auth/idata.php") || ($disppage == "ldap/ldap.php") || ($disppage == "ldap/adduser.php") || ($disppage == "auth/quota.php") || ($disppage == "auth/access.php") || ($disppage == "auth/importpdc.php")){ %>
    'quotafileserver':gen_hint('<%print _("File Server Quota");%>','<%print _("Enter the disk size limit for this user in MB on the fileserver.");%>'),
    'quotahomedir':gen_hint('<%print _("Home Directory Quota");%>','<%print _("Enter the disk size limit for this user in MB for the users home directory.");%>'),
    'quotamailspool':gen_hint('<%print _("Mail Spool Limit");%>','<%print _("Enter the disk size limit for this user in MB for the users mailbox.");%>'),
    'squidproxyaccess':gen_hint('<%print _("Web Proxy Access");%>','<%print _("If the user is allowed to authenticate himself to gain access to internet sites enable this option");%>'),
    'smbserveraccess':gen_hint('<%print _("File Server Access");%>','<%print _("If the user is allowed access to the file server enable this option.");%>'),
    'dialupaccess':gen_hint('<%print _("Radius Enabled (Default Authentication Profile)");%>','<%print _("Enable or disable the usees autehntication profiles.");%>'),
    'accountsuspended':gen_hint('<%print _("Suspended");%>','<%print _("Enable this option to suspend the users account.");%>'),
    'maxaliases':gen_hint('<%print _("Maximum Number Of Aliases");%>','<%print _("Enter the maximum number of aliases a user may have per mailbox.");%>'),
    'maxwebaliases':gen_hint('<%print _("Maximum Number Of Websites");%>','<%print _("Enter the maximum number of websites a user may host in his home directory.");%>'),
    'maxmailboxes':gen_hint('<%print _("Maximum Number Of Mail Boxes");%>','<%print _("Enter the maximum number of additional mail boxes the user may create.") . "<P>" . _("A additional mailbox allows a additional mailbox to be created seperately from the main mailbox with a seperate login and password.");%>'),
    'buid':gen_hint('<%print _("Computer Name");%>','<%print _("The name of the computer you are adding to the domain.Please ensure this name matches with that on the computer");%>'),
    'givenname':gen_hint('<%print _("Firstname");%>','<%print _("The users firstname or contact person in a company");%>'),
    'sn':gen_hint('<%print _("Surname");%>','<%print _("The users surname or company name");%>'),
    'clearpassword':gen_hint('<%print _("Password");%>','<%print _("Enter a password that will be used with this user when imported into the system.");%>'),
    'PW1':gen_hint('<%print _("Password");%>','<%print _("Enter a password that will be used with this user when imported into the system.");%>'),
    'PW2':gen_hint('<%print _("Confirm Password");%>','<%print _("Enter the password above again to confirm it.");%>'),
    'pass1':gen_hint('<%print _("Password");%>','<%print _("Enter a password that will be used with this user when imported into the system.");%>'),
    'pass2':gen_hint('<%print _("Confirm Password");%>','<%print _("Enter the password above again to confirm it.");%>'),
    'cn':gen_hint('<%print _("Common Name (Unique Name For Contact)");%>','<%print _("This is normaly the complete name of the user as they wish to be known.");%>'),
    'uid':gen_hint('<%print _("User Name");%>','<%print _("This is the users login name and should be lowercase and not contain the @ sign.The username is unique and there cannot be duplicate usernames on the system.") . "<P><B>" . _("Reserved Usernames") . "</B><UL><LI>" . _("root - System Administrator") . "</LI><LI>" . _("admin - System Administrator") . "</LI><LI>" . _("bin - System Account") . "</LI><LI>" . _("fax - System Account") . "</LI><LI>" . _("uucp - System Account") . "</LI><LI>" . _("mysql - MySQL Server") . "</LI><LI>" . _("pgsql - pgSQL Server") . "</LI><LI>" . _("postgres - Cubit Accounting") . "</LI><LI>" . _("asterisk - Asterisk Voip Server") . "</LI><LI>" . _("sshd - SSH Seperation User") . "</LI><LI>" . _("www - Web Server") . "</LI><LI>" . _("sweep - Sophos Anti Virus User") . "</LI><LI>" . _("clamav - Clam Anti Virus User") . "</LI><LI>" . _("smmsp - Mail Role Account") . "</LI><LI>" . _("majordomo - Mailing List Manager") . "</LI><LI>" . _("nobody - Unprivliged User") . "</LI></UL>";%>'),
    'givenName':gen_hint('<%print _("Firstname");%>','<%print _("The users firstname or contact person in a company");%>'),
    'userPassword':gen_hint('<%print _("User Password");%>','<%print _("This is the password associated with this account.Your password should not be word and should contain a mix of upper and lowercase letters, numbers and punctuation marks");%>'),
    'userPassword2':gen_hint('<%print _("Confirm Password");%>','<%print _("As the password is not displayed it is neacecery to confirm it.");%>'),
    'title':gen_hint('<%print _("Title");%>','<%print _("The title is that by witch the user is known and includes Mr/Ms/Mrs/Dr/Rev....");%>'),
    'mail':gen_hint('<%print _("Email address");%>','<%print _("The contact address of the user.") . "<P><B>" . _("NOTE!!") . "</B>" . _("This is not neacesaryly the email address on the server but the prefered contact address");%>'),
    'initials':gen_hint('<%print _("Initials");%>','<%print _("The users initials");%>'),
    'telephoneNumber':gen_hint('<%print _("Work Telephone Number");%>','<%print _("This is the main telephone number and will be searched by phones that can access the database.");%>'),
    'facsimileTelephoneNumber':gen_hint('<%print _("Work Fax Number");%>','<%print _("Enter the users work FAX number.");%>'),
    'homePhone':gen_hint('<%print _("Home Telephone Number");%>','<%print _("Enter the users home telephone number.");%>'),
    'otherFacsimiletelephoneNumber':gen_hint('<%print _("Home FAX Number");%>','<%print _("If the user has a FAX at home enter it here.");%>'),
    'mobile':gen_hint('<%print _("Cellphone Number");%>','<%print _("Enter the users cell phone number.");%>'),
    'pager':gen_hint('<%print _("Pager");%>','<%print _("If the user has a pager number/details enter them here");%>'),
    'IPPhone':gen_hint('<%print _("IP Phone Number");%>','<%print _("Enter the users VOIP number.");%>'),
    'conferenceInformation':gen_hint('<%print _("Netmeeting Info");%>','<%print _("If the user has netmeeting information enter it here.");%>'),
    'comment':gen_hint('<%print _("Notes");%>','<%print _("Genral notes regarding the user.");%>'),
    'postalAddress':gen_hint('<%print _("B Postal Address");%>','<%print _("The users work address.");%>'),
    'postalCode':gen_hint('<%print _("B Postal Code");%>','<%print _("The users work postal code.");%>'),
    'l':gen_hint('<%print _("City");%>','<%print _("The city the user resides in.");%>'),
    'st':gen_hint('<%print _("Region (Province/State)");%>','<%print _("Enter the provice that the user resides in.");%>'),
    'c':gen_hint('<%print _("ISO Country Code");%>','<%print _("Enter the country code where the user resides this is not to be confused with the international dialing code.");%>'),
    'homePostalAddress':gen_hint('<%print _("Home Address");%>','<%print _("The users home address");%>'),
    'o':gen_hint('<%print _("Organization");%>','<%print _("The organisation the user works for/represents.");%>'),
    'ou':gen_hint('<%print _("Division");%>','<%print _("The division or department the user is involved with.");%>'),
    'physicalDeliveryOfficeName':gen_hint('<%print _("Office Name/Number");%>','<%print _("The name or number of the users office.");%>'),
    'URL':gen_hint('<%print _("Bussiness Web Site");%>','<%print _("The website the user would like others to see on there profile");%>'),
    'description':gen_hint('<%print _("Domain Name");%>','<%print _("When creating a certificate it is optional and recomended to include the users domain name.");%>'),
    'ipHostNumber':gen_hint('<%print _("IP Address");%>','<%print _("If the certificate is for use on a IP address or if the user has a IP address it can be added.");%>'),
    'mailLocalAddress':gen_hint('<%print _("Email Address");%>','<%print _("All users on the system have a mailbox attached to there usernames and where there is not a explicit email address created for &lt;mailbox&gt;@&lt;domain&gt; where domain is a accepted domain on the system mail will be deposited in the users mail box.This default behavior is acceptable and in most cases prefered but when hosting multiple domains or hosting a domain with a catch all mailbox it is neacecary to fine tweak the behavior by explicitly routing mail to a mail box.Please note a address can only be added when the domain is a valid accepted domain and the user has not reached there alias quota.") . "<P><B>" . _("Mail Flow") . "</B><P><OL><LI>" . _("Is there a explicit alias/virtual alias matching the destination address") . "</LI><LI>" . _("Is there a default mail box @&lt;domain&gt; (nothing in front of the domain)") . "</LI><LI>" . _("Does the mailbox match a user or mail list (the portion brfore the @") . "</LI></OL>";%>'),
    'hostedSite':gen_hint('<%print _("Hosted Web Site");%>','<%print _("Each user is able create websites linked to his username however for the website to be reachable the DNS records for the site need to be appropriately setup.");%>'),
    'certificateGenerate':gen_hint('<%print _("Pass Phrase");%>','<%print _("Enter the certificate pass phrase and please note it is not a password it is a phrase.As with passwords it needs to be secure consiting of upper and lowercase letters,numbers and punctuation marks.A single word (password) is acceptable but not recomended.");%>'),
    'certificateGenerate2':gen_hint('<%print _("Confirm Pass Phrase");%>','<%print _("This is only required if you are generating a new private key bellow.As the pass phrase is not shown confirming the pass phrase is required once used the pass phrase is not stored so only you will be aware of it.");%>'),
    'certificateGenerate3':gen_hint('<%print _("Action To Perform");%>','<%print _("There are 3 types of updates that can be performed.") . "<P><B>" . _("Descriptions") . "</B></P><OL><LI>" . _("Update Certificate - This is a basic update to your public certificate the certificate pass phrase needs to be supplied if you wish to update your public and private key chain.If no password is supplied only the public key chain is updated.") . "</LI><LI>" . _("Create A New Public Certificate - Useing the existing private key create a new public certificate revokeing the old one (it will need to be signed by a administrive user and updated as above once signed).") . "</LI><LI>" . _("Create A New Private Key And Public Certificate - This is basicialy the begin from scratch option and the pass phrase needs to be supplied and confirmed once the certificate has been signed by a administrive user it will need to be updated as above.") . "</LI></OL>";%>'),
    'radiusrealm':gen_hint('<%print _("Authentication Realm");%>','<%print _("Enter the authentication realm users in this zone use to authenticate with when conecting via radius.");%>'),
    'VZ0':gen_hint('<%print _("Virtual Zone To Edit");%>','<%print _("Select the vitrtual zone you wish to edit and click modify bellow");%>'),
    'VZ1':gen_hint('<%print _("Virtual Zone To Add");%>','<%print _("Enter the name of the  vitrtual zone you wish to create and click add bellow");%>'),
    'VZ2':gen_hint('<%print _("Existing Members");%>','<%print _("Members of a virtual zone are the administrators of that zone and can add/edit users in that zone.") . "<BR>" . _("Select a existing member and click delete bellow to remove them.");%>'),
    'VZ3':gen_hint('<%print _("Possible Members");%>','<%print _("These are eligable user accounts on the server that may be added to the virtual zone by selecting the user you wish to add and clicking add bellow.");%>'),
  <%} else if ($disppage == "cdr/vadmin.php") { %>
    'PS0':gen_hint('<%print _("Area Code");%>','<%print _("Local area code to determine local calls and to be prefixed onto any 7 digit dialed numbers.");%>'),
    'PS1':gen_hint('<%print _("Exchange Prefix");%>','<%print _("This is the 3 digits after your area code in your numbers");%>'),
    'PS2':gen_hint('<%print _("PSTN Trunk");%>','<%print _("This is your connection to the telephone network and can either be ISDN or Digium (ZAP) you can choose upto 4 links in the order of preferance if a call fails on one it will try the others");%>'),
    'PS3':gen_hint('<%print _("VOIP Routing");%>','<%print _("If a call matches or exceeds this class of service a VOIP call will be attempted befor a trunk call.");%>'),
    'PS4':gen_hint('<%print _("Trunk Prefix");%>','<%print _("If you need to prefix all trunk calls with a number enter it here as opposed to requireing users to enter it.");%>'),
    'PS5':gen_hint('<%print _("Trunk Strip");%>','<%print _("If you need to strip numbers off calls to the trunk enter the number of digits to strip.");%>'),
    'PS6':gen_hint('<%print _("VOIP Fallover");%>','<%print _("If a call fails on the trunk and it would not normaly be routed via VOIP should it be routed by VOIP.");%>'),
    'PS7':gen_hint('<%print _("ENUM Lookup");%>','<%print _("Should dialed numbers be looked up for a free VOIP route.Where there is a VOIP system connected to a trunk owners of that system can register there trunk numbers to be linked to there VOIP numbers allowing inbound calls free.");%>'),
    'PS8':gen_hint('<%print _("Use GSM Routers");%>','<%print _("Where there are GSM routers connected in a Digium (ZAP) group to the server it is possible to configure them for use as a fail over trunk aswell as for balanced routing of out going cellular calls.");%>'),
    'PS9':gen_hint('<%print _("Trunk Fail Over For GSM");%>','<%print _("When there are GSM routers for celular calls and the routers are busy or otherwise unavailable it is possible to use the configured trunks for any calls that would otherwise fail.");%>'),
    'PS10':gen_hint('<%print _("Default Attendant");%>','<%print _("Set the inbound route when there is no recsptionist logged in and there is no DDI route for the called number");%>'),
    'PS11':gen_hint('<%print _("FAX Terminal");%>','<%print _("Select a extension that will be used as the default FAX terminal for detected inbound FAXES.Please note this requires a FAX machine to be connected to a telephone adapter or to a Digium Port (ZAP)");%>'),
    'PS12':gen_hint('<%print _("Extension Permision");%>','<%print _("This is the extension permistion that is inherited by all new extensions,it can be changed on creation and is purely a convinient starting point");%>'),
    'PS13':gen_hint('<%print _("Default FAX Mailbox");%>','<%print _("This is the email address that will be sent all incoming faxes when there is no FAX terminal selected");%>'),
    'PS14':gen_hint('<%print _("Default Ring Timeout");%>','<%print _("This is the default ring timeout inherited by the extensions on creation");%>'),
    'PS15':gen_hint('<%print _("Default Extension Prefix");%>','<%print _("This will allow users to dial a 2 digit number and have it prefixed with this prefix automaticaly.If there is no local prefix defined (new system) adding the prefix here will create it as a local prefix.");%>'),
    'PS16':gen_hint('<%print _("Default CLI");%>','<%print _("This is the default CLI to request on outgoing calls when there is no CLI configured for the extension");%>'),
    'PS17':gen_hint('<%print _("Default Queue Timeout");%>','<%print _("The absolute timeout inherited by a call queue on creation");%>'),
    'PS18':gen_hint('<%print _("Default Queue Agent Timeout");%>','<%print _("The default ammount of time a call will ring a extension in a queue inherited by a call queue on creation");%>'),
    'PS19':gen_hint('<%print _("Default Queue Agent Penalty");%>','<%print _("The default agent penalty inherited by a queue on creation the higher the value the lower the priority of the agent");%>'),
    'PS20':gen_hint('<%print _("Admin Password");%>','<%print _("Enter a four digit password that is required for priviledged numbers and * codes.");%>'),
    'PS21':gen_hint('<%print _("Confirm Password");%>','<%print _("Enter the password above again to confirm it as it is not visable.");%>'),
    'PS22':gen_hint('<%print _("Number Of ISDN Ports");%>','<%print _("Enter the number of ISDN ports to be used on the system or 0 for none");%>'),
    'PS23':gen_hint('<%print _("Immeadiate Route");%>','<%print _("If there is no MSN or DDI information on the line it is neasesary to route the call immeadiately as there is no routing information assigned to the incoming call.");%>'),
    'PS24':gen_hint('<%print _("Round Robin Routing");%>','<%print _("Balance the load accross all the ISDN connections only available where there are more than one ISDN lines.");%>'),
  <%} else if ($disppage == "cdr/ddiadmin.php") { %>
    'DA0':gen_hint('<%print _("Direct Dial Inward Delete");%>','<%print _("Select a route to be deleted or the option to add a new route.To update a existing route select the add option and type in its DDI bellow and the new destination.");%>'),
    'DA1':gen_hint('<%print _("New DDI To Map");%>','<%print _("Enter the DDI as it is recived it is often a 7 digit number with MSN and 4 digit number with DDI");%>'),
    'DA2':gen_hint('<%print _("Destination");%>','<%print _("Enter the destination to route to for the above DDI");%>'),
  <%} else if ($disppage == "cdr/lpreadmin.php") { %>
    'LP0':gen_hint('<%print _("Local Prefix Admin");%>','<%print _("Select a prefix to delete or the option to add a new prefix.When deleteing a prefix all extensions linked to it will be deleted at this time.");%>'),
    'LP1':gen_hint('<%print _("Add New Prefix");%>','<%print _("If you have selected add new prefix above enter the new prefix here and click submit bellow.");%>'),
  <%} else if ($disppage == "cdr/lareaadmin.php") { %>
    'LA0':gen_hint('<%print _("Local Area Admin");%>','<%print _("Select either a area code to delete or the option to add a new area code.Area codes on this list in addition to your area code are concidered local calls when dialed allowing users with local only call access to dial these areas.");%>'),
    'LA1':gen_hint('<%print _("Add New Area");%>','<%print _("Enter the area code that you want to add to the access list as a local call.");%>'),
  <%} else if ($disppage == "cdr/htmlphone.php") { %>
    'WP0':gen_hint('<%print _("Access Phones Web Interface");%>','<%print _("Certain phones have web interfaces that can be accessed to check status and make changes to the configuration.To make it easier to access these phones we list any phones that may have this feature are listed for you to select and open there web site by clicking on the button bellow");%>'),
  <%} else if ($disppage == "cdr/resync.php") { %>
    'LA0':gen_hint('<%print _("Linksys ATA Auto Configuration");%>','<%print _("Select the Linksys ATA to configure or add a new Linksys ATA to manage");%>'),
    'LA1':gen_hint('<%print _("Description");%>','<%print _("A descriptive name for this Linksys ATA as it will be the devices hostname you are restricted to one word.");%>'),
    'LA2':gen_hint('<%print _("IP Address");%>','<%print _("The current IP address of the device you adding and is found by dialing **** then 110.This IP needs to be reachable from your workstation.");%>'),
    'LA3':gen_hint('<%print _("MAC Address");%>','<%print _("The MAC address of the device you adding it is found on the sticker on the back of the unit or by dialing **** then 140.");%>'),
    'LA4':gen_hint('<%print _("STUN Server");%>','<%print _("Should the device require STUN please enter the STUN server in here.");%>'),
    'LA5':gen_hint('<%print _("Settings Server");%>','<%print _("This is the hostname/IP that the device will connect to to periodicaly download settings and obtain the initial configuration and needs to be correct.The settings server needs to be accessable from the Linksys unit.");%>'),
    'LA6':gen_hint('<%print _("Add A Line");%>','<%print _("6");%>'),
    'LA7':gen_hint('<%print _("Select Extension To Add");%>','<%print _("Select a extension that will be added to this device the extension needs to exist and not have a MAC address in its profile.");%>'),
  <%} else if ($disppage == "cdr/routesetup.php") { %>
    'IB0':gen_hint('<%print _("Delete/Add Route");%>','<%print _("Select a route to delete or the option to add a new route bellow.");%>'),
    'IB1':gen_hint('<%print _("Dialed Prefix");%>','<%print _("Enter the prefix (first 2 of 4 digits) that are dialed to access this route.Please note this may not be a local prefix.Should the destination prefix be the same as a local prefix the dialed prefix can be any non local prefix but the called prefix bellow must be the dsstinations prefix.");%>'),
    'IB2':gen_hint('<%print _("Destination Address");%>','<%print _("Enter the destinations public internet address or hostname.");%>'),
    'IB3':gen_hint('<%print _("Called Prefix");%>','<%print _("Enter the prefix that must be dialed on the remote server to access the extension in most cases this will be the same as the dialed prefix the exception is when both sites have the same local prefix or when there is a existing route to the remote prefix.");%>'),
    'IB4':gen_hint('<%print _("Protocol");%>','<%print _("Select the protocol for the call IAX2 is prefered however SIP is available as a option if required.");%>'),
  <%} else if ($disppage == "cdr/csvupload.php") { %>
    'CU0':gen_hint('<%print _("File To Upload");%>','<%print _("Type in the filename of the file you wish to upload or click the browse button to browse your hard drive to find the file.Please make sure you select the correct file in the right format as failure to do so could lead to loss of data and service");%>'),
    'CU1':gen_hint('<%print _("What To Upload");%>','<%print _("Select the information you are uploading.");%>'),
  <%} else if ($disppage == "cdr/snomload.php") { %>
    'SL0':gen_hint('<%print _("Snom 300 Firmware File To Upload");%>','<%print _("Type in the filename of the file you wish to upload or click the browse button to browse your hard drive to find the file.Please make sure you select the correct file as failure to do so could lead to unpredictible behaviour.");%>'),
    'SL1':gen_hint('<%print _("Snom 320 Firmware File To Upload");%>','<%print _("Type in the filename of the file you wish to upload or click the browse button to browse your hard drive to find the file.Please make sure you select the correct file as failure to do so could lead to unpredictible behaviour.");%>'),
    'SL2':gen_hint('<%print _("Snom 360 Firmware File To Upload");%>','<%print _("Type in the filename of the file you wish to upload or click the browse button to browse your hard drive to find the file.Please make sure you select the correct file as failure to do so could lead to unpredictible behaviour.");%>'),
  <%} else if ($disppage == "cdr/gsmroute.php") { %>
    'GR0':gen_hint('<%print _("Select Router");%>','<%print _("Select the GSM router to configure.There can be more than one router available for use distributed accross the internet.");%>'),
    'GR1':gen_hint('<%print _("Select Channel");%>','<%print _("Select a channel to add or the option to add a new user.");%>'),
    'GR2':gen_hint('<%print _("New Channel");%>','<%print _("If you selected to add a new channel above enter the channel number to use (Zap port).");%>'),
    'GR3':gen_hint('<%print _("Calltime Available");%>','<%print _("Enter the call time that is available on this channel in minutes and seconds.");%>'),
    'GR4':gen_hint('<%print _("Start Time");%>','<%print _("Hour of the day this channel becomes available for calls.");%>'),
    'GR5':gen_hint('<%print _("End Time");%>','<%print _("Hour of the day this channel becomes unavailable for calls.");%>'),
    'GR6':gen_hint('<%print _("Numbers To Match");%>','<%print _("A regex expresion to match against the dialed number to determine eligibiity on this channel,Leave blank to match all numbers.") . "<P><B>" . _("Example") . "</B><P><UL><LI>" . _("All 072 or 082 numbers - \"(0[78]2)\"") . "</LI><LI>" . _("All Cell Numbers - \"(^08[2-47])|(^07[2-4689])\"") . "</LI></UL>";%>'),
    'GR7':gen_hint('<%print _("Expiry");%>','<%print _("Select the date after whitch this channel becomes invalid.");%>'),
    'GR8':gen_hint('<%print _("In Use");%>','<%print _("You may mark this channel in or out of use.");%>'),
    'GR9':gen_hint('<%print _("Out Of Service");%>','<%print _("Set this channel in or out of service.The time it has been in or out of service is shown.By marking the channel out of service you disable the channel for 30 minutes.");%>'),
    'GR10':gen_hint('<%print _("Fault Count");%>','<%print _("This is the current fault count and indicates number of faults since last sucsesfull call.The penalty is the last penalty used to set the the channel out of service by.");%>'),
  <%} else if ($disppage == "auth/snompass.php") { %>
    'SP0':gen_hint('<%print _("Password");%>','<%print _("Enter the password used by phones to access the address book.");%>'),
    'SP1':gen_hint('<%print _("Password Confirmation");%>','<%print _("As the password is not shown on the page you need to confirm it incase there is a mistake.");%>'),
  <%} else if ($disppage == "auth/passwd.php") { %>
    'AP0':gen_hint('<%print _("Password");%>','<%print _("Enter a new administrator password.Please note this change takes time to complete and may disrupt service for sevral minutes.");%>'),
    'AP1':gen_hint('<%print _("Password Confirmation");%>','<%print _("As the password is not shown on the page you need to confirm it incase there is a mistake.");%>'),
  <%} else if ($disppage == "auth/ps2pdf.php") { %>
    'PDF':gen_hint('<%print _("Select File To Convert");%>','<%print _("Type in the filename of the postscript file you wish to convert to the PDF format or click the browse button to browse your hard drive to find the file.");%>'),
  <%} else if ($disppage == "reception/c2c.php") { %>
    'QC0':gen_hint('<%print _("Number To Dial");%>','<%print _("Enter the number you wish to dial or a valid SIP number.") . "<P><B>" . _("Sip Number Format") . "</B><P>&lt;EXTEN&gt;@&lt;DOMAIN&gt;";%>'),
    'QC1':gen_hint('<%print _("Enter A Call Back Number");%>','<%print _("If you wish this call to go to a number other than your extension enter it here.");%>'),
  <%} else if (($disppage == "cdr/mkacd.php") || ($disppage == "cdr/agents.php")) { %>
    'QS0':gen_hint('<%print _("Configure Call Queue");%>','<%print _("Select the queue to configure or the option to add a new queue bellow.");%>'),
    'QS1':gen_hint('<%print _("New Queue");%>','<%print _("Enter a value between 00 and 99 this prefixed by a 5 will be the queue number");%>'),
    'QS2':gen_hint('<%print _("Call Routing Scheme");%>','<%print _("This is the method used to distribute calls to agents in the queue when a call is placed to the queue.") . "<P><B>" . _("Available Options") . "</B></P><UL><LI>" . _("Ring All Agents - All logged in agents will recive the call simultaneously") . "</LI><LI>" . _("Round Robin - The call will be placed with one agent at a time and be sequentialy rotated") . "</LI><LI>" . _("Random - Randomly place the call with a agent") . "</LI><LI>" . _("Least Recent Call - Place the call with the agent who has been idle the longest") . "</LI><LI>" . _("Fewest Calls - Place the call with the agent who has taken the fewest calls") . "</LI></UL>";%>'),
    'QS3':gen_hint('<%print _("Description");%>','<%print _("Enter a description for this queue");%>'),
    'QS4':gen_hint('<%print _("Email Address");%>','<%print _("Enter the email address any voice mail messages must be sent to");%>'),
    'QS5':gen_hint('<%print _("Queue Length");%>','<%print _("Enter the maximum number of waiting calls for this queue or 0 for no limit.Any calls over the limit will be allowed to leave a voicemail message.");%>'),
    'QS6':gen_hint('<%print _("Queue Weight Factor");%>','<%print _("The weight is only taken into account when a agent is a candidate for a call to one or more queue,the queue with the highest weight will be allowed to route to the agent.");%>'),
    'QS7':gen_hint('<%print _("Service Level");%>','<%print _("This is used for statistical putposes to determine if calls are been answered within this time frame (seconds)");%>'),
    'QS8':gen_hint('<%print _("Queue Timeout");%>','<%print _("This is the period a call may be held in the queue before timeing out and be offered the ability to leave a message or continue to hold.");%>'),
    'QS9':gen_hint('<%print _("Default Agent Penalty");%>','<%print _("This is the penalty all agents will inherit when joining this queue and can be altered in the ACD agents section please note the agent(s) with the lowest penalty will be allocated the call first used in conjunction with the queue weight it is the means of fine tuning the routing scheme");%>'),
    'QS10':gen_hint('<%print _("Agent Timeout");%>','<%print _("The time a agents phone should ring before been timed out and waiting the retry delay before been rerouted to a agent");%>'),
    'QS11':gen_hint('<%print _("Retry Delay");%>','<%print _("The delay in seconds between a unsucsesfull call and rerouting it to the queue");%>'),
    'QS12':gen_hint('<%print _("Agent Answer Delay");%>','<%print _("The delay in seconds between the time the call is answered and the call is connected this value should be as low as possible (0 in most cases)");%>'),
    'QS13':gen_hint('<%print _("Agent Wrapup Time");%>','<%print _("The time in seconds between the agent completeing a call and been eligable for a new call.");%>'),
    'QS14':gen_hint('<%print _("Announcement Frequency");%>','<%print _("Enter the time period between announcing the callers position in the queue this can be disabled bellow");%>'),
    'QS15':gen_hint('<%print _("Round Hold Time");%>','<%print _("Enter a value to round the announced hold time to.");%>'),
    'QS16':gen_hint('<%print _("Autologoff Delay");%>','<%print _("If a agent has not taken a call for this period of time and a call to the agent fails the agent will be logged out of the queue.");%>'),
    'QS17':gen_hint('<%print _("Ring Delay");%>','<%print _("Set the time in seconds the call will ring to the caller before been placed in the queue");%>'),
    'QS18':gen_hint('<%print _("Announce Holdtime");%>','<%print _("Select whether the hold time should be periodicaly announced to the caller.");%>'),
    'QS19':gen_hint('<%print _("Play Music On Hold");%>','<%print _("Select if music on hold should be played as opposed to ringing.");%>'),
    'QS20':gen_hint('<%print _("Voicemail Password");%>','<%print _("Password used to access the voicemail box.");%>'),
    'QS21':gen_hint('<%print _("Confirm Password");%>','<%print _("Confirm the voicemail password by retypeing it.");%>'),
    'AS0':gen_hint('<%print _("Select Queue");%>','<%print _("Select the queue whose agents you wish to edit.");%>'),
    'AS1':gen_hint('<%print _("Activate/Deactivate Agent");%>','<%print _("Click on the box bellow to activate (green) or deactivate (red) a agent.");%>'),
    'AS2':gen_hint('<%print _("Agent Name");%>','<%print _("If the agent is a local extension the name of the agent is displayed");%>'),
    'AS3':gen_hint('<%print _("Agent Number");%>','<%print _("The number that is called to place a call to the agent.Click on it to delete the agent.");%>'),
    'AS4':gen_hint('<%print _("Agent Penalty");%>','<%print _("This is the agents queue penalty agents with the eliagable lowest penalty will recive calls first.Alter the penalty by clicking on the link.");%>'),
    'AS5':gen_hint('<%print _("Add Agent");%>','<%print _("Enter the agents number here alter the penalty if required and click add.");%>'),
    'AS6':gen_hint('<%print _("Mailbox/Forward On Timeout");%>','<%print _("Enter the mailbox to use afterhours and when this extension is not available when a inbound call times out.");%>'),
  <%} else if ($disppage == "ssl/index.php") { %>
    'SS0':gen_hint('<%print _("Sign SSL Request");%>','<%print _("Enter the file name of the certificate request to sign or click browse to select the file.");%>'),
    'SS1':gen_hint('<%print _("Email To Send Certificate");%>','<%print _("Once signed the certificate can be emailed to the owner,enter the owners address here");%>'),
    'SS2':gen_hint('<%print _("Sign As CA Certificate");%>','<%print _("If this certificate will be allowed to sign other certificates enable this option.");%>'),
  <%} else if ($disppage == "auth/maildel.php") { %>
    '0':gen_hint('<%print _("Remote Delivery Address");%>','<%print _("This is the address that will be used to deliver email and may be either a mailbox name or a full email address.The default is to use the users mailbox (there username) if a full email address is used that does not reside on the server the mail will be routed to the appropriate server.");%>'),
    '1':gen_hint('<%print _("Server To Redirect Mail To");%>','<%print _("If this is set the email will be forwarded to this server for procesing.When a email is processed in this way the to address changes to that set in the remote delivery address first.If the redirect server is the server reciving the mail it will be delivered.");%>'),
    '2':gen_hint('<%print _("Out Of Office Reply");%>','<%print _("If this is set and it is activated (bellow) then when a mail is recived for the user this text will be sent.Please note only one copy will be sent per recipient per week.");%>'),
    '3':gen_hint('<%print _("Activate Out Of Office Reply");%>','<%print _("When enabled the out of office reply will be procesed.Please note changing this option is not real time and requires upto 30 minutes");%>'),
  <%} else if ($disppage == "auth/mailbox.php") { %>
    'MB1':gen_hint('<%print _("Select Mailbox/Create Mail Box");%>','<%print _("Select the mailbox you wish to edit or create a new mailbox (default)");%>'),
    'MB2':gen_hint('<%print _("New Mailbox Login");%>','<%print _("If you have selected add mailbox above you will need to enter the mailbox name the same rules apply for a system user in that the mail name must be unique and not a reserved name.") . "<P><B>" . _("Reserved Usernames") . "</B><UL><LI>" . _("root - System Administrator") . "</LI><LI>" . _("admin - System Administrator") . "</LI><LI>" . _("bin - System Account") . "</LI><LI>" . _("fax - System Account") . "</LI><LI>" . _("uucp - System Account") . "</LI><LI>" . _("mysql - MySQL Server") . "</LI><LI>" . _("pgsql - pgSQL Server") . "</LI><LI>" . _("postgres - Cubit Accounting") . "</LI><LI>" . _("asterisk - Asterisk Voip Server") . "</LI><LI>" . _("sshd - SSH Seperation User") . "</LI><LI>" . _("www - Web Server") . "</LI><LI>" . _("sweep - Sophos Anti Virus User") . "</LI><LI>" . _("clamav - Clam Anti Virus User") . "</LI><LI>" . _("smmsp - Mail Role Account") . "</LI><LI>" . _("majordomo - Mailing List Manager") . "</LI><LI>" . _("nobody - Unprivliged User") . "</LI></UL>";%>'),
    'MB3':gen_hint('<%print _("Owners Name");%>','<%print _("This is the fullname of the owner of this mailbox.");%>'),
    'MB4':gen_hint('<%print _("Server To Redirect Mail To");%>','<%print _("If this is set the email will be forwarded to this server for procesing.When a email is processed in this way the to address changes to that set in the remote delivery address first.If the redirect server is the server reciving the mail it will be delivered.");%>'),
    'MB5':gen_hint('<%print _("Password");%>','<%print _("Enter the mailbox password.");%>'),
    'MB6':gen_hint('<%print _("Confirm Password");%>','<%print _("Confirm the password by retyping the mailbox password.");%>'),
    'MB7':gen_hint('<%print _("Remote Delivery Address");%>','<%print _("This is the address that will be used to deliver email and may be either a mailbox name or a full email address.The default is to use the users mailbox (there username) if a full email address is used that does not reside on the server the mail will be routed to the appropriate server.");%>'),
    'MB8':gen_hint('<%print _("Email Address");%>','<%print _("All users on the system have a mailbox attached to there usernames and where there is not a explicit email address created for &lt;mailbox&gt;@&lt;domain&gt; where domain is a accepted domain on the system mail will be deposited in the users mail box.This default behavior is acceptable and in most cases prefered but when hosting multiple domains or hosting a domain with a catch all mailbox it is neacecary to fine tweak the behavior by explicitly routing mail to a mail box.Please note a address can only be added when the domain is a valid accepted domain and the user has not reached there alias quota.") . "<P><B>" . _("Mail Flow") . "</B><P><OL><LI>" . _("Is there a explicit alias/virtual alias matching the destination address") . "</LI><LI>" . _("Is there a default mail box @&lt;domain&gt; (nothing in front of the domain)") . "</LI><LI>" . _("Does the mailbox match a user or mail list (the portion brfore the @") . "</LI></OL>";%>'),
  <%} else if ($disppage == "auth/radius.php") { %>
    'RP1':gen_hint('<%print _("Add/Modify Realm");%>','<%print _("Select the profile to edit or add a new profile (bellow) if you select add new realm (default).");%>'),
    'RP2':gen_hint('<%print _("New Realm");%>','<%print _("Enter the realm to add to the users profile.");%>'),
    'RP3':gen_hint('<%print _("Active");%>','<%print _("Activate or deactivate this profile.Please note the default profile needs to be activated or deactivated in the access control settings (Allow radius access)");%>'),
    'RP4':gen_hint('<%print _("Port Type");%>','<%print _("Select the service type for this profile.");%>'),
    'RP5':gen_hint('<%print _("IP Address");%>','<%print _("Enter the IP address allocated to the user if the user has a static address or enter the means the address is assigned.") . "<P>" . _("Special Addresses") . "</P><ul><LI>" . _("Automatic Assigned - 255.255.255.254") . "</LI><LI>" . _("User Assigned - 255.255.255.255") . "</LI></UL>";%>'),
    'RP6':gen_hint('<%print _("MTU");%>','<%print _("Set the MTU recomendation for this profile this is not always honored but should be set correctly.A MTU of 1500 is best for normal connections DSL connections need lower MTU often 1400-1492");%>'),
    'RP7':gen_hint('<%print _("Comperssion");%>','<%print _("Select wether to enable or disable IP header compression.");%>'),
    'RP8':gen_hint('<%print _("Simultaneous Use");%>','<%print _("Enter the ammount of simultaneous times this profile may be used.");%>'),
    'RP9':gen_hint('<%print _("Session Timeout");%>','<%print _("Enter the period in seconds the session will stay active (86000 = 1day).");%>'),
    'RP10':gen_hint('<%print _("Idle Timeout");%>','<%print _("Disconnect the connection id idle for more than this period of time in seconds.");%>'),
    'RP11':gen_hint('<%print _("Interim Accounting Interval");%>','<%print _("Send accounting updates periodicaly (seconds) this is recomended to prevent loss of data.");%>'),
    'RP12':gen_hint('<%print _("Reply Item");%>','<%print _("Enter the name of any item that needs to be sent to the remote server you will be prompted for its value.");%>'),
    'RP13':gen_hint('<%print _("Check Item");%>','<%print _("Enter the name of any item that needs to be verified you will be prompted for its value.");%>'),
  <%} else if ($disppage == "auth/pwexp.php") { %>
    'sambapwdcanchange':gen_hint('<%print _("Date/Time Password May Change");%>','<%print _("The user may only change the password after this date/time.");%>'),
    'sambapwdlastset':gen_hint('<%print _("Date/Time Password Was Last Set");%>','<%print _("The password was last changed at this date and time.");%>'),
    'sambapwdmustchange':gen_hint('<%print _("Date/Time Password Expires");%>','<%print _("The user will not be able to log in (currently only the fileserver service is affected) if he has not changed his password by this date.");%>'),
  <%} else if (($disppage == "ldap/mmaps.php") || ($disppage == "ldap/mclass.php")) { %>
    'virtuserkey':gen_hint('<%print _("Local Address");%>','<%print _("This is the email address you are creating,the email address needs to be within a accepted domain.Please note this overwrites any other email routing.");%>'),
    'virtuservalue':gen_hint('<%print _("Delivery Address");%>','<%print _("If the new virtual address you creating is to be redirected to a alternate address enter it here.");%>'),
    'virtuseraction':gen_hint('<%print _("Error Message");%>','<%print _("Should you want all mail to this new virtual address to be bounced and rejected enter the message to reject the mail with here.");%>'),
    'mailerkey':gen_hint('<%print _("Domain To Redirect");%>','<%print _("Enter the domain name that you want to redirect to a alternate server here.");%>'),
    'mailervalue':gen_hint('<%print _("Server To Be Redirected To");%>','<%print _("Enter the SMTP server to redirect all mail from the above domain");%>'),
    'accesskey':gen_hint('<%print _("Address");%>','<%print _("Enter the server name or IP address of the server you are blacklisting");%>'),
    'domainkey':gen_hint('<%print _("Original Domain");%>','<%print _("Enter the domain you are rewriting.");%>'),
    'domainvalue':gen_hint('<%print _("Rewrite To");%>','<%print _("Enter the domain that it will be rewritten to.");%>'),
    'hordekey':gen_hint('<%print _("Email Domain");%>','<%print _("Enter the domain to be used when requests originate from the server bellow");%>'),
    'hordevalue':gen_hint('<%print _("Web Address");%>','<%print _("Enter the address that users for the above domain will be using");%>'),
    'exist':gen_hint('<%print _("Existing Entry");%>','<%print _("Select A existing maping from the list to delete");%>'),
    'R':gen_hint('<%print _("Accepted Domain For Relaying/Spooling");%>','<%print _("Enter the domain name of the domain to be allowed to relay mail through the server or spool and forward mail on the server.");%>'),
    'LDAPRoute':gen_hint('<%print _("Accepted Domain");%>','<%print _("Enter the name of a domain that you wish to accept and deliver mail for.Please note that mail needs to arrive at the server this can be done ensureing the DNS records are created appropriatly");%>'),
    'M':gen_hint('<%print _("Masqueraded Domain");%>','<%print _("Enter any domains that you wish to masquerade.");%>'),
    'WhiteList':gen_hint('<%print _("Email Address");%>','<%print _("Enter email address to be added to the white list and be excluded from any spam filter.");%>'),
    'VirusSafe':gen_hint('<%print _("Email Address");%>','<%print _("Enter email address to be added to the white list and be excluded from any virus scan.");%>'),
 <%} else if ($disppage == "ldap/maliases.php") { %>
    'MA1':gen_hint('<%print _("Edit Existing List");%>','<%print _("Select the alias to add from the list and clik modify below without filling in any other field.");%>'),
    'MA2':gen_hint('<%print _("New List To Be Created");%>','<%print _("Enter the name of the mailing list you are creating");%>'),
    'MA3':gen_hint('<%print _("Initial Entry");%>','<%print _("A mailing list cannot be created empty so a initial entry needs to be supplied to create the list");%>'),
    'MA4':gen_hint('<%print _("Type Of List");%>','<%print _("There are 2 types of lists the fist the simple list has no management or features addresses can be added or deleted via this interface.The second type of list has many features and it is possible to subscribe, unsubscribe,moderate and manage the list via email.When creating a complex list only administrators can be added or subtracted via this interface the initial entry supplied will be the administrator.") . "<P><B>" . _("Configureing A Complex List") . "</B></P>" . _("Send A message to majordomo@&lt;domain&gt; with config &lt;listname&gt;-list &lt;listname&gt;-list.admin in the message body.Once done you will recive a email with all the config options edit it and send it back as plain text.The first line of the email must be newconfig &lt;listname&gt;-list &lt;listname&gt;-list.admin and end the email with EOF on a line by itself.");%>'),
    'MA5':gen_hint('<%print _("Delete");%>','<%print _("Select a entry to remove from the list and click delete bellow");%>'),
    'MA6':gen_hint('<%print _("Add Entry");%>','<%print _("Enter a address to add to the mailing list and click add bellow");%>'),
 <%} else if (($disppage == "ldap/ugroup.php") || ($disppage == "ldap/agroup.php")){ %>
    'SG1':gen_hint('<%print _("Edit Group");%>','<%print _("Select the group you wish to edit and click modify bellow.");%>'),
    'SG2':gen_hint('<%print _("Add New Group");%>','<%print _("Enter the group name bellow supply a description and click add.Once the group is addded select it from the list above and click modify.");%>'),
    'SG3':gen_hint('<%print _("Group Description");%>','<%print _("Enter a description for the group you are adding.");%>'),
    'SG4':gen_hint('<%print _("Existing Members");%>','<%print _("Select a member from the list to delete from the group.");%>'),
    'SG5':gen_hint('<%print _("Posible Members");%>','<%print _("Select a user from the list to add to the group.");%>'),
 <%} else if ($disppage == "auth/sslcert.php") { %>
    'Sign':gen_hint('<%print _("Sign This Certificate");%>','<%print _("Once you have verified the information in the certificate as correct and wish to authorise it click the sign request button.It is adviseable to notify the user it has been signed and request they update there key chains by going into the SSL options filling in there pass phrase and requesting a update.");%>'),
 <%} else if ($disppage == "ldap/ennav.php") { %>
    '0':gen_hint('<%print _("Search Criteria");%>','<%print _("Select the criteria to search for");%>'),
    '1':gen_hint('<%print _("Match Criteria");%>','<%print _("Select how to match the criteria");%>'),
    '2':gen_hint('<%print _("Search Value");%>','<%print _("Enter what to search for to narrow down the results.If no value is entered all results will be displayed");%>'),
 <%} else if ($disppage == "auth/migratevz.php") { %>
    '0':gen_hint('<%print _("Move User From One Zone To Another");%>','<%print _("Select the zone you wish to move the user to and click submit the users profile will be rewriten as appropriate for that zone.");%>'),
 <%} else if (($disppage == "cdr/mkzap.php") || ($disppage == "cdr/mkspan.php") || ($disppage == "cdr/mkzapc.php")){ %>
    'Z0':gen_hint('<%print _("Select Trunk Group To Edit");%>','<%print _("Select the trunk group you wish to configure there are only 4 available.");%>'),
    'Z1':gen_hint('<%print _("Select Span To Configure");%>','<%print _("Select a span to configure from the list and click add/modify bellow.");%>'),
    'Z2':gen_hint('<%print _("Add New Span");%>','<%print _("Enter the span number of the span you are adding and click add modify bellow to configure it.");%>'),
    'Z3':gen_hint('<%print _("Add New Channel To Group");%>','<%print _("Enter the channel or channel range to be added to this group and the RX/TX gain.") . "<P><B>" . _("Examples") . "</B><UL><LI>" . _("1-4 : Channels 1 through 4 inclusive") . "</LI><LI>" . _("1-4,13,20 : Channels 1 through 4 13 and 20") . "</LI></UL>";%>'),
    'signalling':gen_hint('<%print _("Group Signaling");%>','<%print _("Select the signaling to be used by this group.");%>'),
    'jitterbuffers':gen_hint('<%print _("Number Of Jitterbuffers");%>','<%print _("Enter the number of 20ms jitterbuffers to use to improve quality please note that useing a high value increases latency.");%>'),
    'faxdetect':gen_hint('<%print _("Fax Detection");%>','<%print _("Choose how to detect and process fax calls on this group.");%>'),
    'echocancel':gen_hint('<%print _("Enable Echo Cancelation");%>','<%print _("This is a software based echo canceleation facility that can help eliminate echo.") . "<BR>" . _("Ensureing the RX/TX gain is set correctly and calibration of the echo coeficients.");%>'),
    'echotraining':gen_hint('<%print _("Echo Training");%>','<%print _("Allows the system to calibrate the echo canclelation software by sending a impulse at the begining of the call while the channel is muted.");%>'),
    'echocancelwhenbridged':gen_hint('<%print _("Enable Echo Cancelation On Bridged Calls");%>','<%print _("A call bridged between TDM lines should not need echo cancelation and this can concerve the CPU load on the server however in some cases it improves the quality of a call.");%>'),
    'toneduration':gen_hint('<%print _("DTMF Tone Duration");%>','<%print _("Set the length in ms that DTMD tones will be played on the line when DTMF is relayed onto the group.");%>'),
    'relaxdtmf':gen_hint('<%print _("Relax DTMF Detection");%>','<%print _("It may be neacesary to be more forgiving in detecting DTMF tones on the trunk however this may lead to DTMF signals been falsly identified.");%>'),
    'dtmfduplicatedelay':gen_hint('<%print _("DTMF Duplicate Delay");%>','<%print _("On some lines the DTMF tones can be echoed back onto the circit and detected again this allows you to set a timer (ms) where after a DTMF pulse a duplicate will be rejected for this time period.") . "<BR>" . _("Setting this value to high can block DTMF pulses when typed quickly by the user.");%>'),
    'busydetect':gen_hint('<%print _("Hangup Detection");%>','<%print _("Trunk lines do not properly detect the end of a call and it is neacesary to listen on the line for the busy signal when the dialed party disconects and if detected disconnect the call.") . "<BR>" . _("This feature is most recomended and to enable it check the checkbox.");%>'),
    'busycount':gen_hint('<%print _("Hanugup Detection Count");%>','<%print _("When hangup detection is enabled the system will hangup when it hears this many repititions of the pattern bellow.");%>'),
    'busypattern':gen_hint('<%print _("Hangup Detection Pattern");%>','<%print _("Enter the pattern of the the hangup signal it has two time values (ms) seperated by a comma the first value is the on time (length of the beep) and the second value is the off time (length of silence).") . "<P><B>" . _("Common Values Are") . "</B></P><UL><LI>" . _("2500,500 (Long Sound 2.5 Seconds Followed By Short Silence 1/2 Second)") . "</LI><LI>" . _("500,500 (Equal Length Sound And Silence Of 1/2 Second)") . "</LI></UL>";%>'),
    'callprogress':gen_hint('<%print _("Enable Call Progress Detection");%>','<%print _("This is a feature where a call is monitored and RING/ANSWER is detected.This feature is not able to properly detect calls made on most systems and as such should be left off");%>'),
    'progzone':gen_hint('<%print _("Call Progress Zone");%>','<%print _("Enter the zone for call progress detection currently us,ca,br,cr and uk we are hoping to support south africa soon.");%>'),
    'ringtimeout':gen_hint('<%print _("Ring Timeout");%>','<%print _("The ammount of time a call can ring before been hungup this is only available when call progress detection is enabled.");%>'),
    'usecallerid':gen_hint('<%print _("Enable Callerid");%>','<%print _("Should caller id information be attemted to be sent/recived.");%>'),
    'cidsignalling':gen_hint('<%print _("Caller ID Signaling");%>','<%print _("Select the method used recive/send callerid");%>'),
    'cidstart':gen_hint('<%print _("Caller ID Trigger");%>','<%print _("Select what trigers the caller id to be recived.");%>'),
    'sendcalleridafter':gen_hint('<%print _("Caller ID Ring Delay");%>','<%print _("Set the number of rings to wait before reciving caller ID when the trigger is ring.");%>'),
    'answeronpolarityswitch':gen_hint('<%print _("Polarity Reversal Answer");%>','<%print _("This is a alternative to call progress detection and will reliably detect answer.Please note most lines do not offer this feature however many cell routers do.");%>'),
    'polarityonanswerdelay':gen_hint('<%print _("Polarity On Answer Delay");%>','<%print _("Ignore any polarity reversals for this period after answer as some times the polarity will reverse for a pulse and if polarity reverse on hangup is requested the call will be hung up when the polarity reverts.");%>'),
    'hanguponpolarityswitch':gen_hint('<%print _("Hangup On Polarity Reversal");%>','<%print _("When a call is in progress and the polarity is reversed the call will be terminated.");%>'),
    'switchtype':gen_hint('<%print _("ISDN Switch Type");%>','<%print _("Should this be a group atached to a span using pri signaling the switchtype needs to be set correctly.");%>'),
    'overlapdial':gen_hint('<%print _("Enable Overlap Dialing");%>','<%print _("This is required for DDI routing of calls.");%>'),
    'resetinterval':gen_hint('<%print _("Unused Channel Reset Interval");%>','<%print _("Set this value to a value greater than 0 to allow reseting of all unused channels periodicaly.The interval is a value in seconds.");%>'),
    'priindication':gen_hint('<%print _("PRI Progress Indications");%>','<%print _("Send call progress information in or outofband outofband is the prefered method however some channel banks may require inband indication.");%>'),
    'usecallingpres':gen_hint('<%print _("Allow Calling Number Presentation");%>','<%print _("This will allow the system to set the number it wishes to be used to be presented to the called party.This may not be available on all systems.");%>'),
    'restrictcid':gen_hint('<%print _("Caller ID Withheld");%>','<%print _("Do not display caller id on any outgoing calls.");%>'),
    'timingsource':gen_hint('<%print _("Span Timing Source");%>','<%print _("The timing source parameter determines whether the clock signal from the far end of the T1/E1 is used as the master source of clock timing. If it is, our own clock will synchronise to it. T1/E1s connected directly or indirectly to a PSTN provider (telco) should generally be the first choice to sync to. The PSTN will never be a slave to you. You must be a slave to it.") . "<P>" . _("Choose 1 to make the equipment at the far end of the E1/T1 link the preferred source of the master clock. Choose 2 to make it the second choice for the master clock, if the first choice port fails (the far end dies, a cable breaks, or whatever). Choose 3 to make a port the third choice, and so on. If you have, say, 2 ports connected to the PSTN, mark those as 1 and 2. The number used for each port should be different.") . "<P>" . _("If you choose 0, the port will never be used as a source of timing. This is appropriate when you know the far end should always be a slave to you. If the port is connected to a channel bank, for example, you should always be its master. Any number of ports can be marked as 0.") . "<P>" . _("Incorrect timing sync may cause clicks/noise in the audio, poor quality or failed faxes, unreliable modem operation, and is a general all round bad thing.") . "<P>";%>'),
    'lbo':gen_hint('<%print _("Line Build Out");%>','<%print _("The line build-out (or LBO) is an integer, from the following table:") . "<P><UL><LI>" . _("0: 0 db (CSU) / 0-133 feet (DSX-1)") . "</LI><LI>" . _("1: 133-266 feet (DSX-1)") . "</LI><LI>" . _("2: 266-399 feet (DSX-1)") . "</LI><LI>" . _("3: 399-533 feet (DSX-1)") . "</LI><LI>" . _("4: 533-655 feet (DSX-1)") . "</LI><LI>" . _("5: -7.5db (CSU)") . "</LI><LI>" . _("6: -15db (CSU)") . "</LI><LI>" . _("7: -22.5db (CSU)") . "</LI></UL";%>'),
    'framing':gen_hint('<%print _("Framing");%>','<%print _("The framing is one of \"d4\" or \"esf\" for T1 or \"cas\" or \"ccs\" for E1 Note: \"d4\" could be referred to as \"sf\" or \"superframe\"");%>'),
    'coding':gen_hint('<%print _("Coding");%>','<%print _("The coding is one of \"ami\" or \"b8zs\" for T1 or \"ami\" or \"hdb3\" for E1");%>'),
    'crc4':gen_hint('<%print _("E1 CRC4 Checking");%>','<%print _("E1 lines may have CRC4 checking and if this is the case it needs to be enabled");%>'),
    'yalarm':gen_hint('<%print _("Transmit Yellow Alarm");%>','<%print _("Should the yellow alarm (no channels in use) be transmited.");%>'),
    'dchannel':gen_hint('<%print _("Dchannel");%>','<%print _("In the case of a PRI enter the channel number of the D channel.");%>'),
 <%} else if (($disppage == "auth/dnsadmin.php") || ($disppage == "dnsadmin.php")) { %>
    'DNS1':gen_hint('<%print _("Domain To Modify");%>','<%print _("Select the domain or class of domain to modify.");%>'),
    'DNS2':gen_hint('<%print _("Domain Name");%>','<%print _("If you chose a class of domain above you must explicitly enter the domain name.");%>'),
    'DNS3':gen_hint('<%print _("Start Of Authority Time To Live");%>','<%print _("This is the value in seconds that the SOA record will be valid in cache before having to be reloaded.");%>'),
    'DNS4':gen_hint('<%print _("Start Of Authority Mail Record");%>','<%print _("Contact information for the domain.");%>'),
    'DNS5':gen_hint('<%print _("Domain Serial Number");%>','<%print _("Used by slave servers to determine if a new copy of the domain must be loaded when the domain is refreshed.");%>'),
    'DNS6':gen_hint('<%print _("Refresh Interval");%>','<%print _("The interval between updating the domain on slave servers in seconds.");%>'),
    'DNS7':gen_hint('<%print _("Retry Interval");%>','<%print _("If a refresh was unsucsesfull the server will retry periodicly specified by this interval.");%>'),
    'DNS8':gen_hint('<%print _("Expiry Time");%>','<%print _("The time that a record may expire and be removed from a cache server.");%>'),
    'DNS9':gen_hint('<%print _("Minimum Time");%>','<%print _("The time to live of negitive responses.");%>'),
    'DNS10':gen_hint('<%print _("New Record");%>','<%print _("Enter the name of the new record to add to the zone.");%>'),
    'DNS11':gen_hint('<%print _("TTL For Record");%>','<%print _("Enter the TTL of the new record.");%>'),
    'DNS12':gen_hint('<%print _("Record Type");%>','<%print _("Select the type of record you adding.");%>'),
    'DNS13':gen_hint('<%print _("Record Value");%>','<%print _("Enter the value of the new record in the format required by the type.");%>'),
    'DNSU1':gen_hint('<%print _("Enter Domain Name");%>','<%print _("Enter the name of the domain you wish to edit.");%>'),
    'DNSU2':gen_hint('<%print _("Domain Password");%>','<%print _("Enter the password for the above domain.");%>'),<%
  } else if ($disppage == "auth/photo.php") {
    if ((isset($_SESSION['pstart'])) && (isset($_SESSION['phend']))) {
      print "\n";
      for($pcnt=$_SESSION['pstart'];$pcnt<=$_SESSION['phend'];$pcnt++) {
        print "      '" . $pcnt  . "':gen_img('" . $_SESSION['euser'] . "_" . $pcnt . "'),\r\n";
      }
    } else {%>
    'photo':gen_img('<%print $_SESSION['classi'];%>'),
    '0':gen_hint('<%print _("Browse For Photo");%>','<%print _("Type in the filename of the photo you wish to add to the album or click the browse button to browse your hard drive to find the photo.Please not only JPEG photos are accepted and the ratio of width to height must be greater than 1:2.");%>'),
    '1':gen_hint('<%print _("Insert Photo");%>','<%print _("If you wish to insert the selected photo at a specific position select it here and click modify");%>'),
    '2':gen_hint('<%print _("Replace Photo");%>','<%print _("If you wish to replace the photo at a specific position with the photo selected above select the position and click modify");%>'),
    '3':gen_hint('<%print _("Delete Photo");%>','<%print _("If you wish to delete a photo you may do so by selecting its position and clicking modify.it is not neacesary to select a photo above but you cannot delete all photos there must be at least one in the album.");%>'),
  <%}}%> 
}

var myHint = new THints (HINTS_CFG, HINTS_ITEMS);

function gen_hint(h_title,h_text) {
	return '<TABLE CLASS=hint><TR><TH CLASS=heading-body2>'+h_title+'</TH></TR><TR CLASS=hint><TD>'+h_text+'</TD></TR></TABLE>';
}

function gen_img (s_file) {
	return '<table CLASS=hint><tr><td ALIGN=CENTER VALIGN=MIDDLE><img src=/photo/'+s_file+'.jpg></td></tr></table>';
}
