#!/bin/sh

if [ "${FIRMWARE}" ] && [ "${DEVPATH}" ] && [ -e /sys/${DEVPATH}/loading ];then
  if [ -e "/usr/lib/hotplug/firmware/${FIRMWARE}" ];then
    echo 1 > /sys/${DEVPATH}/loading
    cat /usr/lib/hotplug/firmware/${FIRMWARE} > /sys/${DEVPATH}/data
    echo 0 > /sys/${DEVPATH}/loading
   elif [ -e "/lib/firmware/${FIRMWARE}" ];then
    echo 1 > /sys${DEVPATH}/loading
    cat /lib/firmware/${FIRMWARE} > /sys/${DEVPATH}/data
    echo 0 > /sys${DEVPATH}/loading
   else
    echo -1 > /sys${DEVPATH}/loading
  fi;
fi;
