#!/bin/bash

#    Copyright (C) 2002  <Gregory Hinton Nietsky>
#    Copyright (C) 2005  <ZA Telecomunications>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#Start up firewall
if [ -x /etc/rc.d/rc.firewall ];then
  /etc/rc.d/rc.firewall startup > /dev/null 2>&1
fi;


#Start SSHD
if [ ! -e /etc/ssh_host_key ];then
  ssh-keygen -t rsa1 -f /etc/ssh_host_key -N "" > /dev/null 2>&1
fi;
for sshkey in dsa rsa ecdsa ed25519;do
  if [ ! -e /etc/ssh_host_${sshkey}_key ];then
    ssh-keygen -t ${sshkey} -f /etc/ssh_host_${sshkey}_key -N "" > /dev/null 2>&1
  fi;
done;
(ulimit -n 65535;/usr/sbin/sshd > /dev/null 2>&1) &

#Startup DNS Server
if [ ! -e /etc/rndc.key ];then
  /usr/sbin/rndc-confgen -a -r /dev/urandom > /dev/null 2>&1
fi;
if [ -e /etc/named.conf ];then
  (ulimit -n 65535;/usr/sbin/named > /dev/null 2>&1) &
fi;

#Start DHCP As Soon As Posible
if [ ! -d /var/state/dhcp ];then
  mkdir -p /var/state/dhcp
fi;
touch /var/state/dhcp/dhcpd.leases /var/state/dhcp/dhcpd6.leases
if [ -e /etc/dhcpd.conf ];then
  (ulimit -n 65535;/usr/sbin/dhcpd > /dev/null 2>&1) &
fi;

#Start SNMP
/usr/sbin/snmpd -c /etc/snmpd.conf UDP:161 UDP6:161

#ACPI Deamon
/usr/sbin/acpid > /dev/null 2>&1

