#!/bin/bash

/sbin/ip route add ${ifconfig_pool_remote_ip} dev vpn0 table Link
/sbin/ip route add ${ifconfig_pool_remote_ip}/32 dev vpn0 src ${ifconfig_local} table Ipsec
/sbin/ip addr add ${ifconfig_pool_local_ip}/30 dev vpn0

/sbin/iptables -I OVPNIN -j SYSIN -s ${ifconfig_pool_remote_ip}/32
/sbin/iptables -I OVPNOUT -j SYSOUT -d ${ifconfig_pool_remote_ip}/32
/sbin/iptables -I OVPNFWD -j ACCEPT -d ${ifconfig_pool_remote_ip}/32
/sbin/iptables -I OVPNFWD -j ACCEPT -s ${ifconfig_pool_remote_ip}/32

