#!/bin/bash

#    Copyright (C) 2002  <Gregory Hinton Nietsky>
#    Copyright (C) 2005  <ZA Telecomunications>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#Set file-max
echo 1228800 > /proc/sys/fs/file-max

#Turn On Syn Flood Protection
echo 1 >/proc/sys/net/ipv4/tcp_syncookies

#Turn Off Explicit Congestion Notification (for broken firewalls)
echo 0 >/proc/sys/net/ipv4/tcp_ecn

#Turn Off TCP Window Scaling (for broken firewalls)\
echo 0 > /proc/sys/net/ipv4/tcp_window_scaling

#Dump Tasks When Out Of Memory set overcommit to swap + 80% of ram
echo 1 > /proc/sys/vm/oom_dump_tasks
echo 0 > /proc/sys/vm/overcommit_memory
echo 100 > /proc/sys/vm/overcommit_ratio
