#!/bin/bash


NARCH=${NARCH:=$(uname -m)}

if [ ! "${3}" ] || [ ! -d "${2}" ];then
  echo "$0 <ARCH> <INSTDIR> <GROUP TO INSTALL....>";
  exit
fi;

ARCH=${1}
shift

INSTDIR=${1}
shift;

case ${ARCH} in
  x86_32)ARCHKERN="linux-intel-dts";
    EXTRABASE="${ARCHKERN}-wanpipe.x86_64";;
  x86_64|i686)ARCHKERN="linux-intel-dts";
    EXTRABASE="${ARCHKERN}-wanpipe.${ARCH}";;
  *)ARCHKERNEL="";
    EXTRABASE="";;
esac;

do_yuminstall() {
  YINSTROOT=${1}
  shift

  case ${ARCH} in
    x86_64)yum -y --installroot=${YINSTROOT} --exclude="*.x86_32 *.i686" install $@;;
    x86_32)yum -y --installroot=${YINSTROOT} --exclude="*.x86_64 *.i686" install $@;;
    i[3-6]86)yum -y --installroot=${YINSTROOT} --exclude="*.x86_64 *.x86_32" install $@;;
    arm|armv7l)yum -y --installroot=${YINSTROOT} --exclude="*.armv6l" install $@;;
    armv6|armv6l)yum -y --installroot=${YINSTROOT} --exclude="*.armv7l" install $@;;
    ppc)yum -y --installroot=${YINSTROOT} --exclude="*.ppc64" install $@;;
    ppc64)yum -y --installroot=${YINSTROOT} --exclude="*.ppc" install $@;;
    mips)yum -y --installroot=${YINSTROOT} --exclude="*.mips64" install $@;;
    mips64)yum -y --installroot=${YINSTROOT} --exclude="*.mips" install $@;;
    *)yum -y --installroot=${YINSTROOT} --exclude="*.x86_64 *.x86_32 *.i686" install $@;;
  esac;
}

install_to_dir() {
  INSTDIR=${1}
  shift;

  for dir in root proc sys dev tmp initrd media media/isofs media/install run run/udev;do
    if [ ! -d ${INSTDIR}/${dir} ];then
      mkdir ${INSTDIR}/${dir}
    fi;
  done
  chmod 1777 ${INSTDIR}/tmp
  RPM_PKG_LIST="";
  for pkggrp in $@;do
    IFS=- read -a PKG_ARR <<< ${pkggrp}
    if [ "${RPM_PKG_LIST}" ];then
      RPM_PKG_LIST+=" ${pkggrp}"
     else
      RPM_PKG_LIST="${pkggrp}"
    fi;
    if [ "${pkggrp:0:1}" == "@" ];then
      for spkg in libs conf locale;do
        RPM_PKG_LIST+=" ${pkggrp}-${spkg}"
      done;
    fi;
    if [ "${pkggrp:1}" == "buildroot" ];then
      RPM_PKG_LIST+=" ${pkggrp}-dev @root-dev @core-dev guile-dev gc-dev systemd-dev libatomic_ops-dev
        libunistring-dev libevent-dev libpaper-dev gtk+-dev
        gdk-pixbuf-dev atk-dev Mesa-dev gtk3-dev qt-4-dev";
      if [ "${ARCHKERN}" ];then
        RPM_PKG_LIST+=" ${ARCHKERN}-dev";
      fi;
     elif [ "${pkggrp:1}" == "root" ];then
      if [ "${ARCHKERN}" ];then
        for kernpkg in dahdi firmware modules;do
          RPM_PKG_LIST+=" ${ARCHKERN}-${kernpkg}.${ARCH}";
        done;
        RPM_PKG_LIST+=" ${ARCHKERN}.${ARCH}";
      fi;
      if [ "${EXTRABASE}" ];then
        RPM_PKG_LIST+=" ${EXTRABASE}";
      fi;
    fi;
  done
  do_yuminstall ${INSTDIR} ${RPM_PKG_LIST}
}

if [ ! -d /etc/rpm ];then
  mkdir /etc/rpm
fi;

case ${ARCH} in
  arm|armv7*)echo "armv7l-distrotech-linux-gnu" > /etc/rpm/platform;;
  armv6*)echo "armv6l-distrotech-linux-gnu" > /etc/rpm/platform;;
  arm64)echo "aarch64-distrotech-linux-gnu" > /etc/rpm/platform;;
  mips)echo "mips32-distrotech-linux-gnu" > /etc/rpm/platform;;
  *)echo "${ARCH}-distrotech-linux-gnu" > /etc/rpm/platform;;
esac;

install_to_dir ${INSTDIR} $@

rm /etc/rpm/platform
