#!/bin/bash

if [ -e /var/run/crond.pid ];then
  if [ ! -s /var/run/crond.pid ];then
    killall -9 crond > /dev/null 2>&1
   elif [ ! -d /proc/`cat /var/run/crond.pid` ];then
    killall -9 crond > /dev/null 2>&1
  fi;
 else
  killall -9 crond > /dev/null 2>&1
fi;

if [ ! -d /var/spool/cron/crontabs ];then
  mkdir -p /var/spool/cron/crontabs
fi;

if [ ! -d /var/spool/cron/cronstaps ];then
  mkdir -p /var/spool/cron/cronstamps
fi;

if [ ! -d /etc/cron.d ];then
  mkdir -p /etc/cron.d
fi;

if [ ! "`pidof crond`" ];then
  echo $$ > /var/run/crond.pid
  exec /usr/sbin/crond -f >> /var/log/cron 2>&1

  if [ -e /root/crontab ];then
    crontab /root/crontab -u root
  fi;
fi
