#!/bin/bash

/usr/sbin/grub-mkdevicemap --no-floppy
if [ -e /boot/grub/devicemap.local ];then
  cat /boot/grub/devicemap.local >> /boot/grub/device.map
fi;

DCNT=0

#Ensure swap space has a UUID
blkid -t TYPE=swap -o device |awk '{printf "\
  if [ ! \"`blkid %s -s UUID`\" ];then\
    swapoff %s;\
    mkswap %s;\
    swapon %s;\
  fi\n",$1,$1,$1,$1,$1}' |sh > /dev/null 2>&1

#Install grub on all lvm VG PV's
for hdisk in `pvdisplay -c 2>/dev/null |awk -F: '$2 == "lvm" {printf "%s\n",$1}'`;do
  DEV=`grub-probe --target=drive -d ${hdisk} |sed -e "s/\(.*\),.*/\1)/"`
  echo "Installing GRUB on ${DEV}"
  /usr/sbin/grub-install --force ${DEV}
  if [ $? == 0 ];then
    let DCNT++
  fi;
done

#If there is no LVM install on the drive with /boot
if [ ${DCNT} == 0 ];then
  DEV=`grub-probe --target=drive /boot |sed -e "s/\(.*\),.*/\1)/"`
  if [ $? == 0 ] && [ "${DEV}" != "(lvm-root)" ];then
    echo "Installing GRUB on ${DEV}"
    /usr/sbin/grub-install --force ${DEV}
    if [ $? == 0 ];then
      let DCNT++
    fi;
  fi;
fi;

if [ ${DCNT} != 0 ];then
  /usr/sbin/mkinitrd
 else
  echo "Grub NOT Installed"
  exit -1
fi;
