#!/bin/bash

asterisk -rx "stop now"
sleep 1;
while [ `pidof asterisk` ];do
  sleep 2;
  asterisk -rx "stop now"
  sleep 1;
done;

if [ -d /sys/module/wanpipe ];then
  wanrouter stop
  WANPIPE=1;
fi;

if [ -d /sys/module/hfcsusb ];then
  ISDN_USB=1;
fi;

if [ -d /sys/module/hfcpci ];then
  ISDN_PCI=1;
fi;

if [ -d /sys/module/hfcmulti ];then
  ISDN_MULTI=1;
fi;

(rmmod wctc4xxp dahdi_transcode dahdi_dummy wctdm wctdm24xxp wct1xxp wcte11xp wcte12xp wct4xxp dahdi_echocan_mg2 dahdi
rmmod netjetpci hfcsusb hfcpci hfcmulti mISDN_debugtool mISDN_dsp mISDN_dtmf mISDN_x25dte mISDN_isac l3udss1 mISDN_l2 mISDN_l1 mISDN_core
rm /dev/mISDN) > /dev/null 2>&1

if [ "$ISDN_USB" == "1" ];then
  modprobe hfcsusb
fi;
if [ "$ISDN_PCI" == "1" ];then
  modprobe hfcpci
fi;
if [ "$ISDN_MULTI" == "1" ];then
  modprobe hfcmulti
fi;

if [ "$WANPIPE" == "1" ];then
  wanrouter start
fi;

modprobe dahdi_dummy
dahdi_cfg
servconfig
