#!/usr/bin/perl

use Net::LDAPS;

open(LCON,"/etc/ldap.conf");
while(<LCON>) {
  chop $_;
  @centry=split(/\s/,$_);
  if (@centry[0] eq "master_host") {
    $host=@centry[1];
  } elsif (@centry[0] eq "binddn") {
    $binddn=@centry[1];
  } elsif (@centry[0] eq "bindpw") {
    $password=@centry[1];
  }
}

$ldap = Net::LDAPS->new($host,port=>"636",verify => 'none',timeout => "10");
$ldap->bind($binddn,password => $password);

($uid)=getgrnam($ARGV[0]);
if ($uid eq $ARGV[0]) {
  exit 255;
}

$mesg = $ldap->search(base=>"ou=Groups",filter =>"(cn=" . $ARGV[0] . ")",attrs=>['cn']);
if ($mesg->count > 0) {
  exit 255;
}

$mesg = $ldap->search(filter =>"objectClass=posixGroup",
                      attrs=>['gidnumber']);

while($entry = $mesg->shift_entry) {
  $gidnum=$entry->get_value("gidnumber");
  if ($gidnum >= 500) {
    $usedgid{$gidnum}="TRUE";
  }
}

$ucnt=500;
while($usedgid{$ucnt} eq "TRUE") {
  $ucnt++;
}

$res=$ldap->add("cn=$ARGV[0],ou=Groups",attrs => [ objectClass => "posixGroup",cn => $ARGV[0],gidnumber => $ucnt]);
$err=$res->error;

sleep 5;
`/usr/sbin/nscd -i group`
