#!/usr/bin/perl

open(LC,">/etc/asterisk/local.conf");
print LC "TRUNK=CAPI/@ARGV[0]:\n";
close(LC);

open(CC,">/etc/asterisk/capi.conf");

for($cnt=1;$cnt<=@ARGV[1];$cnt++) {
  $conts .=$cnt . ",";
}
chop $conts;

$chancnt=@argv[1]*2;

print CC<<__EOF__;
[general]
nationalprefix=0
internationalprefix=09
rxgain=0.8
txgain=0.8

[interfaces]
msn=@ARGV[0]
incomingmsn=*
controller=$conts
softdtmf=1
accountcode=
context=ddi
echosquelch=1
echocancel=yes
callgroup=1
devices=$chancnt
;echotail=64
;deflect=12345678
__EOF__
close(CC);

`/usr/sbin/asterisk -r -x "extensions reload"`;
`/usr/sbin/asterisk -r -x "reload"`;

