#!/usr/bin/perl

use Net::LDAPS;

open(LCON,"/etc/ldap.conf");
while(<LCON>) {
  chop $_;
  @centry=split(/\s/,$_);
  if (@centry[0] eq "master_host") {
    $host=@centry[1];
  } elsif (@centry[0] eq "rootbinddn") {
    $binddn=@centry[1];
  }
}
close(LCON);

open(LSP,"/etc/ldap.secret");
while(<LSP>) {
  $password=$_;
}
close(LSP);

$ldap = Net::LDAPS->new($host,port=>"636",verify => 'none',timeout => "10");
$ldap->bind($binddn,password => $password);

($uid)=getgrnam($ARGV[0]);
if ($uid ne $ARGV[0]) {
  exit 255;
}

$mesg = $ldap->search(base=>"ou=Groups",filter =>"(cn=" . @ARGV[0] . ")",attrs=>['cn']);

if ($mesg->count ne "1") {
  exit 255;
}

$entry = $mesg->shift_entry;

$res=$ldap->delete($entry->dn);

$err=$res->error;

#sleep 5;
#`/usr/sbin/nscd -i group`
