#!/usr/bin/perl

open(IC,">/etc/asterisk/misdn.conf");

for($cnt=1;$cnt<=@ARGV[0];$cnt++) {
  $conts .=$cnt . ",";
}
chop $conts;

print IC<<__EOF__;
[general]
debug=0
tracefile=/var/log/asterisk/misdn.log
bridging=yes
stop_tone_after_first_digit=yes
append_digits2exten=yes
dynamic_crypt=no
ntdebugflags=0
ntdebugfile=/var/log/asterisk/misdn-nt.log

[default]
allowed_bearers=all
far_alerting=no
rxgain=0
txgain=0
te_choose_channel=yes
l1watcher_timeout=180
pmp_l1_check=yes
hdlc=no
context=ddi
language=en
musicclass=default
method=round_robin
dialplan=4
localdialplan=0
cpndialplan=0
nationalprefix=0
internationalprefix=09
presentation=-1
screen=-1
always_immediate=no
senddtmf=yes
hold_allowed=no
early_bconnect=yes
incoming_early_audio=no
echocancel=yes
echocancelwhenbridged=yes
echotraining=no
need_more_infos=no
jitterbuffer=4000
jitterbuffer_upper_threshold=0
callgroup=1
pickupgroup=1
max_incoming=-1
max_outgoing=-1
faxdetect_context=ddi
faxdetect=incoming
incoming_early_audio=yes
msns=*

[out]
ports=$conts
context=ddi
__EOF__

if (@ARGV[1] != "") {
  print IC "immediate=yes\n";
}
close(IC);

`/usr/sbin/asterisk -r -x "restart when convenient"`;

