#!/bin/bash

/usr/sbin/grub-mkdevicemap --no-floppy
DCNT=0

for hdisk in `pvdisplay -c 2>/dev/null |awk -F: '$2 == "lvm" {printf "%s\n",$1}'`;do
  echo "Installing GRUB on ${hdisk}"
  DEV=`grub-probe --target=drive -d ${hdisk} |sed -e "s/\(.*\),.*/\1)/"`
  /usr/sbin/grub-install --force ${DEV}
  if [ $? == 0 ];then
    let DCNT++
  fi;
done

if [ ${DCNT} == 0 ];then
  DEV=`grub-probe --target=drive /boot |sed -e "s/\(.*\),.*/\1)/"`
  if [ $? == 0 ] && [ "${DEV}" != "(lvm-root)" ];then
    echo "Installing GRUB on ${DEV}"
    /usr/sbin/grub-install --force ${DEV}
    if [ $? == 0 ];then
      let DCNT++
    fi;
  fi;
fi;

if [ ${DCNT} != 0 ];then
  /usr/sbin/mkinitrd
 else
  echo "Grub NOT Installed"
  exit -1
fi;
