#!/bin/bash

/usr/sbin/grub-mkdevicemap --no-floppy

if [ -d /var/boot ];then
  BOOTDIR=/var/boot
 else
  BOOTDIR=/boot
fi;

DCNT=0
for hdisk in `awk '{printf "%s ",$2}' /boot/grub/device.map`;do
  if [ "`pvdisplay -c 2>/dev/null |grep -E "${hdisk}[0-9]:lvm:"`" ];then
    /usr/sbin/grub-install --boot-directory=${BOOTDIR} --force ${hdisk}
    let DCNT++
  fi;
done;

if [ ${DCNT} == 0 ];then
  /usr/sbin/grub-install --force --boot-directory=${BOOTDIR} "(hd0)"
fi;

/usr/sbin/mkinitrd
