#!/bin/bash

init_rd_drivers() {
  kernel=${2}

  for kdir in drivers drivers-ata drivers-scsi drivers-usb;do
    mkdir -p ${3}/lib/modules/${kernel}/${kdir}
  done;

  cp ${1}lib/modules/${kernel}/kernel/drivers/ata/* ${1}lib/modules/${kernel}/kernel/drivers/mmc/host/* ${3}/lib/modules/${kernel}/drivers-ata
  mv ${3}/lib/modules/${kernel}/drivers-ata/ata_generic.ko.gz \
     ${3}/lib/modules/${kernel}/drivers-ata/pata_legacy.ko.gz \
     ${3}/lib/modules/${kernel}/drivers-ata/ahci_platform.ko.gz \
     ${3}/lib/modules/${kernel}/drivers-ata/pata_acpi.ko.gz \
     ${3}/lib/modules/${kernel}/drivers-ata/libahci.ko.gz \
     ${3}/lib/modules/${kernel}/drivers

  cp -r ${1}lib/modules/${kernel}/kernel/drivers/usb/storage/* ${3}/lib/modules/${kernel}/drivers-usb

  for kmod in block/loop.ko.gz base/firmware_class.ko.gz pcmcia mmc/core \
           mmc/card misc/cb710 misc/tifm_core.ko.gz cdrom/cdrom.ko.gz ssb \
           usb/host md/ usb/wusbcore uwb usb/misc/ftdi-elan.ko.gz connector/cn.ko.gz;do
   if [ -f ${1}lib/modules/${kernel}/kernel/drivers/${kmod} ];then
     cp ${1}lib/modules/${kernel}/kernel/drivers/${kmod} ${3}/lib/modules/${kernel}/drivers
    elif [ -d ${1}lib/modules/${kernel}/kernel/drivers/${kmod} ];then
     cp -r ${1}lib/modules/${kernel}/kernel/drivers/${kmod}/* ${3}/lib/modules/${kernel}/drivers
   fi;
  done;

  for kmod in isofs/isofs.ko.gz nls/nls_iso8859-1.ko.gz "ext*/*" "jbd*/*";do
    cp -r ${1}lib/modules/${kernel}/kernel/fs/${kmod} ${3}/lib/modules/${kernel}/drivers
  done;

  for klib in zlib_deflate raid6 lzo libcrc32c.ko.gz crc16.ko.gz crc-t10dif.ko.gz;do
    if [ -f ${1}lib/modules/${kernel}/kernel/lib/${klib} ];then
      cp ${1}lib/modules/${kernel}/kernel/lib/${klib} ${3}/lib/modules/${kernel}/drivers
     elif [ -d ${1}lib/modules/${kernel}/kernel/lib/${klib} ];then
      cp -r ${1}lib/modules/${kernel}/kernel/lib/${klib}/* ${3}/lib/modules/${kernel}/drivers
    fi;
  done;

  for scard in scsi_wait_scan scsi_mod scsi_tgt sd_mod sr_mod "libsas/*" \
            scsi_transport_iscsi scsi_transport_fc scsi_transport_sas \
            scsi_transport_spi "device_handler/*" "megaraid/*";do
    cp ${1}lib/modules/${kernel}/kernel/drivers/scsi/${scard}.ko.gz ${3}/lib/modules/${kernel}/drivers
  done
  cp -r ${1}lib/modules/${kernel}/kernel/crypto ${3}/lib/modules/${kernel}/
}

init_rd_drivers_scsi() {
  cd ${1}lib/modules/${kernel}
  for ADAPTER in `lspci -nm |awk -F\" '$2 == "Class 0100" || $2 == "Class 0101" || $2 == "Class 0102" || $2 == "Class 0103" || $2 == "Class 0104" || $2 == "Class 0106" || $2 == "Class 0107" || $2 == "Class 0180" {printf "grep -E \"%s.*%s\" modules.pcimap\n",$4,$6}' |sh |awk '{print $1}'`${EXTRA_DEV};do 
    if [ "$ADAPTER" == "sym53c8xx" ];then
      ADAPTER="sym53c8xx_2/sym53c8xx";
    fi;
    if [ "$ADAPTER" == "aic79xx" ];then
      ADAPTER="aic7xxx/aic79xx";
    fi;

    if [ -e ${1}lib/modules/${kernel}/kernel/drivers/scsi/$ADAPTER.ko.gz ];then
      cp ${1}lib/modules/${kernel}/kernel/drivers/scsi/$ADAPTER.ko.gz ${3}/lib/modules/${kernel}/drivers-scsi
     elif [ -d ${1}lib/modules/${kernel}/kernel/drivers/scsi/$ADAPTER ];then
      cp -r ${1}lib/modules/${kernel}/kernel/drivers/scsi/$ADAPTER/* ${3}/lib/modules/${kernel}/drivers-scsi
     elif [ -e ${1}lib/modules/${kernel}/kernel/drivers/message/fusion/$ADAPTER.ko.gz ];then
      cp -r ${1}lib/modules/${kernel}/kernel/drivers/message/fusion/* ${3}/lib/modules/${kernel}/drivers-scsi
     elif [ -e ${1}lib/modules/${kernel}/kernel/drivers/message/i2o/$ADAPTER.ko.gz ];then
      cp -r ${1}lib/modules/${kernel}/kernel/drivers/message/i2o/* ${3}/lib/modules/${kernel}/drivers-scsi
    fi;
  done
  cd ${CWD}
}

initrd_init() {
  LOOP=`losetup -f`
  if [ ! "${LOOP}" ] || [ ! -e "${LOOP}" ];then
    return 255
  fi;

  (dd if=/dev/zero of=${1} bs=1M count=${3}
  mkfs.ext2 -F -L initrd -i 1024 ${1}
  losetup ${LOOP} ${1}
  mount ${LOOP} ${2}) >/dev/null 2>&1

  for tld in bin dev etc isofs lib proc sbin sys sysroot var;do
    mkdir ${2}/${tld}
  done

  mkdir -p /var/lock/lvm
  mkdir ${2}/etc/lvm
  for lvmdir in archive backup cache;do
    mkdir ${2}/etc/lvm/${lvmdir}
  done;

  cp /etc/lvm/lvm.conf ${2}/etc/lvm/
  cp /usr/sbin/lvm.static ${2}/sbin/lvm
  cp /usr/bin/modprobe.static ${2}/sbin/modprobe
  cp /sbin/nash ${2}/bin
  cp /sbin/losetup.static ${2}/sbin/losetup
  cp /sbin/mount.static ${2}/bin/mount
  ln -s /proc/mounts ${2}/etc/mtab
  ln -s /sbin/lvm ${2}/sbin/vgchange
  ln -s /sbin/lvm ${2}/sbin/vgscan
  ln -s /sbin/lvm ${2}/sbin/vgmknodes
  ln -s /linuxrc ${2}/sbin/init
  touch ${2}/etc/fstab
}

initrd_config() {
  cat <<_EOF_
#!/bin/nash

mount -t ramfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

mknod /dev/console c 5 1
mknod /dev/urandom c 1 9
mknod /dev/null c 1 3
mknod /dev/systty c 4 0
mknod /dev/zero c 1 5
mknod /dev/ram5 b 1 5
mknod /dev/loop0 b 7 0
mknod /dev/cdrom b 11 0

_EOF_

  for driver in `ls ${1}/lib/modules/${2}-smp/drivers-scsi |cut -d. -f1`;do
    echo "modprobe ${driver}"
  done;

  for driver in `ls ${1}/lib/modules/${2}-smp/drivers-ata |cut -d. -f1`;do
    echo "modprobe ${driver}"
  done;

  cat <<_EOF_

modprobe pata_acpi
modprobe ata_generic
modprobe uhci_hcd
modprobe ohci_hcd
modprobe ehci_hcd
_EOF_

  for driver in `ls ${1}/lib/modules/${2}-smp/drivers-usb |cut -d. -f1`;do
    echo "modprobe ${driver}"
  done;

  cat <<_EOF_
modprobe sd_mod
modprobe scsi_wait_scan

modprobe loop
modprobe dm-mod

_EOF_

  if [ "$USBSLEEP" ];then
    echo "sleep ${USBSLEEP}"
  fi;

#  /sbin/dmraid -c -sa -i > /dev/null 2>&1
#  if [ $? == 0 ];then
#    echo "/sbin/dmraid -ay -i"
#  fi;

  if [ -e /etc/mdadm.conf ];then
    cat <<_EOF_
/sbin/mdadm -Ebsc part > /etc/mdadm.conf
/sbin/mdadm -As
_EOF_
  fi;

  if [ -e /etc/initrd.local ];then
    cat /etc/initrd.local
  fi;

cat <<_EOF_

mkdevices /dev
mkdmnod
vgchange -a y --sysinit lvm
vgmknodes
/bin/mount -o ro -t ext4 -U ${ROOTDEV} /sysroot
echo 0x0100 > /proc/sys/kernel/real-root-dev

pivot_root /sysroot /sysroot/initrd

mount -t ramfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mkdir /dev/udevdb
mkdir /dev/pts
mkdir /dev/shm
mount -t devpts none /dev/pts

udevstart
_EOF_
}

if [ -e /etc/netsentry-version ];then
  eval `cat /etc/netsentry-version`
 elif [ -e /install/netsentry-version ];then
  eval `cat /install/netsentry-version`
 else
  echo "No Config File"
  exit;
fi;

if [ ! -e /lib/modules/${KERNEL}-smp ] || [ ! -e /lib/modules/${KERNEL}-install ];then
  echo No Kernel Directory
  exit;
fi;

if [ "$EXTRA_DEV" ];then
  EXTRA_DEV=" ${EXTRA_DEV}"
fi;

if [ ! -e /boot/grub/device.map ];then
  grub-mkdevicemap
fi;

ROOTDEV=`grub-probe -t fs_uuid / 2>/dev/null`
if [ ! "${ROOTDEV}" ] && [ -e /dev/lvm/root ];then
  ROOTDEV=`blkid -s UUID -o value /dev/lvm/root`
fi;

CWD=`pwd`

initrd_init /tmp/initrd /mnt/initrd 16
cp /etc/modprobe.* /mnt/initrd/etc/

for ktype in smp install;do
  depmod -a -F /boot/System.map-${KERNEL}-${ktype} ${KERNEL}-${ktype}
  init_rd_drivers / ${KERNEL}-${ktype} /mnt/initrd
  init_rd_drivers_scsi / ${KERNEL}-${ktype} /mnt/initrd
  depmod -a -e -F /boot/System.map-${KERNEL}-${ktype} -b /mnt/initrd ${KERNEL}-${ktype}
  rm /boot/vmlinuz-${ktype} /boot/System.map-${ktype} > /dev/null 2>&1
  ln -s vmlinuz-${KERNEL}-${ktype} /boot/vmlinuz-${ktype}
  ln -s System.map-${KERNEL}-${ktype} /boot/System.map-${ktype}
done

initrd_config /mnt/initrd ${KERNEL} > /mnt/initrd/linuxrc
cp /mnt/initrd/linuxrc /tmp/linuxrc
chmod 750 /mnt/initrd/linuxrc

umount /mnt/initrd
losetup -d ${LOOP}

(e2fsck -Dfy /tmp/initrd
dd if=/tmp/initrd bs=1k |gzip -c9 > /boot/initrd-netsentry-$KERNEL
rm /tmp/initrd /boot/initrd-netsentry
ln -s initrd-netsentry-${KERNEL} /boot/initrd-netsentry) > /dev/null 2>&1

/usr/sbin/rdev /boot/vmlinuz-smp /dev/ram0
/usr/sbin/rdev /boot/vmlinuz-install /dev/ram0

grub-mkconfig  > /boot/grub/grub.cfg

if [ -h /boot/boot ];then
  rm /boot/boot
fi;
