#!/bin/bash

if [ "$1" ];then
  mount $1 /mnt -o ro
  if [ $? == 0 ];then
    for bind in dev proc sys;do
      mount --bind /${bind} /mnt/${bind}
    done;
    chroot /mnt fsck -A -p
    mount /mnt -o remount,rw
    rm /mnt/etc/mtab
    touch /mnt/etc/mtab
    chroot /mnt mount -f /
    chroot /mnt swapon -a
    chroot /mnt mount -a -t ext2,ext3,ext4,vfat
    if [ -e /mnt/etc/HOSTNAME ];then
      cp /mnt/etc/hosts /mnt/etc/resolv.conf /etc
      hostname -F /mnt/etc/HOSTNAME
    fi;
    UDEV=`findfs LABEL=UPGRADE`;
    if [ ${UDEV} ];then
      mount ${UDEV} /mnt/mnt/update
      mount --bind / /mnt/mnt/update/mnt/dev
      if [ -e /mnt/var/run/rsyncd.pid ];then
        rm /mnt/var/run/rsyncd.pid
      fi;
      chroot /mnt rsync --daemon --config /etc/rsyncd-update.conf
    fi;
   else
    echo "Mount failed"
  fi;
fi;
