#!/bin/bash

if [ ! "`/sbin/ip rule |grep -E "^110:"`" ];then
  /sbin/ip rule add table 90 prio 110
fi;

if [ ! "`lsmod |grep -E "^dummy"`" ];then
  /sbin/modprobe dummy
  /sbin/ip addr add 127.255.255.253/30 dev dummy0
  /sbin/ip link set dev dummy0 up
fi;

if [ ! "`ip rule list  |grep -E "^80:"`" ];then 
  /sbin/ip route add 127.255.255.252/30 src 127.255.255.253 dev dummy0 scope link table 80
  /sbin/ip rule add table 80 prio 80
fi

/sbin/ip route |awk '{printf "/sbin/ip route add %s dev %s table 80\n",$1,$3}' |sh
