#!/usr/bin/perl

use Net::LDAPS;

open(LCON,"/etc/ldap.conf");
while(<LCON>) {
  chop $_;
  @centry=split(/\s/,$_);
  if (@centry[0] eq "master_host") {
    $host=@centry[1];
  } elsif (@centry[0] eq "rootbinddn") {
    $binddn=@centry[1];
  }
}
close(LCON);

open(LSP,"/etc/ldap.secret");
while(<LSP>) {
  chop $_;
  $password=$_;
}
close(LSP);

$ldap = Net::LDAPS->new($host,port=>"636",verify => 'none',timeout => "10");
$ldap->bind($binddn,password => $password);

if ( -e "/etc/ipsec/d/cacerts/server_cacert.pem") {
  $cacert=`/usr/bin/openssl x509 -in /etc/ipsec.d/cacerts/server_cacert.pem -outform der`;
  $crlcert=`/usr/bin/openssl crl -in /etc/ipsec.d/crls/server_crl.pem -outform der`;
} else {
  $cacert=`/usr/bin/openssl x509 -in /etc/ipsec.d/cacerts/cacert.pem -outform der`;
  $crlcert=`/usr/bin/openssl crl -in /etc/ipsec.d/crls/crl.pem -outform der`;
}

$res=$ldap->modify("cn=Domain",replace => { objectClass => ["device","pkiCA"],
                                            'cAcertificate;binary' => $cacert,
                                            'certificateRevocationList;binary' => $crlcert});
