#!/usr/bin/php -d safe_mode=no
<%

include "/var/spool/apache/htdocs/cdr/auth.inc";
if (! isset($agi)) {
  require_once("/var/lib/asterisk/agi-bin/phpagi/phpagi-asmanager.php");
  $agi=new AGI_AsteriskManager();
}

$agi->connect("127.0.0.1","admin","admin");

$curext=pg_query("SELECT name,ipaddr,(name=secret OR length(secret) > 4 OR secret='' OR secret IS NULL) from users left outer join astdb as lkey on (substr(name,0,3)=lkey.key) LEFT OUTER JOIN astdb AS ptype ON (name=ptype.family AND ptype.key='PTYPE') LEFT OUTER JOIN astdb AS macok ON (name=ptype.family AND macok.key='SNOMMAC') WHERE macok.value != '' AND macok.value IS NOT NULL AND (ptype.value='POLYCOM' OR ptype.value='IP_500' OR ptype.value='IP_600' OR ptype.value='IP_601' OR ptype.value='IP_4000') AND length(name) = 4 AND lkey.family = 'LocalPrefix' AND lkey.value=1");
$num=pg_num_rows($curext);
for($i=0;$i < $num;$i++) {
  $r = pg_fetch_array($curext,$i,PGSQL_NUM);
  if ($r[2] == 't') {
    $newpass=str_pad(rand(0,9999),4,"0",STR_PAD_LEFT);
    $agi->command("sip notify reboot-polycom " . $r[0]);
    pg_query("UPDATE users SET secret='" . $newpass . "' WHERE name='" . $r[0] . "'");
    $agi->command("sip prune realtime user " . $r['0']);
    $agi->command("sip prune realtime peer " . $r['0']);
    $agi->command("sip show peer " . $r[0] . " load");
  } else {
    $agi->command("sip notify reboot-polycom " . $r[0]);
  }
}
$agi->disconnect();
%>
