#!/bin/bash

#New Mail Boxes / Dirs Been Opened To Be Run At Startup
chown root.root /var/spool/mail /var/spool/mail/? /var/spool/mail/?/?
chmod 770 /var/spool/mail /var/spool/mail/? /var/spool/mail/?/?

setfacl -b /var/spool/mail /var/spool/mail/? /var/spool/mail/?/?
setfacl -m u::rwX -m g::rwX -m o::0 -m g:12:rwX -m g:100:rX -m m::rwX \
        -m d:u::rwX -m d:g::rwX -m d:o::0 -m d:g:12:rwX -m d:m::rwX \
        /var/spool/mail /var/spool/mail/? /var/spool/mail/?/?

#Public Store
setfacl -R -b /var/spool/mail/shared
setfacl -m u:bin:rwx /var/spool/mail
setfacl -R -m u:bin:rwX -m d:u:bin:rwX /var/spool/mail/shared/
setfacl -R -m u::rwX -m g::rwX -m o::0 -m g:12:rwX -m m:rwX \
        -m d:u::rwX -m d:g::rwX -m d:o::0 -m d:g:12:rwX -m d:m:rwX \
        /var/spool/mail/shared

#Users folders
setfacl -R -b /var/spool/mail/?/?/*
setfacl -R -m u::rwX -m g::rwX -m o::0 -m g:12:rwX -m m:rwX \
        -m d:u::rwX -m d:g::rwX -m d:o::0 -m d:g:12:rwX -m d:m:rwX \
        /var/spool/mail/?/?/*
