#!/usr/bin/perl

use Net::LDAPS;
use Crypt::PasswdMD5;

open(LCON,"/etc/ldap.conf");
while(<LCON>) {
  chop $_;
  @centry=split(/\s/,$_);
  if (@centry[0] eq "master_host") {
    $host=@centry[1];
  } elsif (@centry[0] eq "rootbinddn") {
    $binddn=@centry[1];
  }
}
close(LCON);

open(LSP,"/etc/ldap.secret");
while(<LSP>) {
  $password=$_;
}
close(LSP);

if (@ARGV[1] eq "") {
  print "Enter Password: ";
  $pass=<STDIN>;
  chop $pass;
} else {
  $pass=@ARGV[1];
}

$ldap = Net::LDAPS->new($host,port=>"636",verify => 'none',timeout => "10");
$ldap->bind($binddn,password => $password);

%rephash = ( clearPassword => $pass);

$ldap->modify("uid=@ARGV[0],ou=Users",replace => { %rephash });
