#!/bin/bash

if [ ! -e "/etc/firewall.conf" ] || [ ! -e "/etc/netsentry-version" ];then
  echo "This does not look like a valid server to upgrade"
  exit 255
fi

eval `cat /etc/netsentry-version`

if [ "${2}" ];then   
  SERV=${2}
 elif [ ! "${RSERV}" ];then
  SERV="127.0.0.1"
 else
  SERV=${RSERV}
fi

/sbin/iptables -I DEFOUT -j ACCEPT -p tcp --dport 873

rsync -az --contimeout=20 rsync://${SERV}/updates/ / > /dev/null 2>&1
RES=$?
if [ ${RES} != 0 ] && [ "${SERV}" != "127.0.0.1" ];then
  SERV=127.0.0.1
  rsync -az --contimeout=20 rsync://${SERV}/updates/ / > /dev/null 2>&1
fi;
RES=$?

if [ "${1}" ] && [ "${KERNEL}" != "${1}" ];then
  UPKERN=${1}
 else
  UPKERN=${KERNEL}
fi;

if [ -d /usr/lib/asterisk/modules-1.8 ];then
  rm -rf /usr/lib/asterisk/modules-1.8
fi;

if [ -d /usr/lib/asterisk/modules ];then
  rm -rf /usr/lib/asterisk/modules
fi;

flashutil upgrade ${UPKERN} ${SERV}
RES=$?

/sbin/iptables -D DEFOUT -j ACCEPT -p tcp --dport 873

exit ${RES}

#Old upgrade postgre to ver 8
#  if [ ! "`psql -V |head -1|grep "8.2.3"`" ];then
#    /usr/bin/pg_dumpall -U pgsql -h 127.0.0.1 -c |gzip -c > /var/tmp/pgsql.sql
#    if [ $? != 0 ];then
#      echo "Upgrade Not Done !!!!"
#      exit -1
#    fi;
#    if [ -s /var/tmp/pgsql.sql ];then
#      /usr/bin/killall -9 crond > /dev/null 2>&1
#      /usr/bin/killall -9 asterisk > /dev/null 2>&1
#      /bin/su pgsql -c "pg_ctl -D /var/spool/pgsql -m immediate stop" > /dev/null 2>&1
#      /usr/bin/killall -9 postmaster > /dev/null 2>&1
#      /usr/bin/rsync ${UROPT} ${SERV}::postgresql /
#      if [ $? != 0 ];then
#        echo "Upgrade Not Done !!!!"
#        exit -1
#      fi;
#      /bin/rm -rf /var/spool/pgsql
#      /etc/rc.d/rc.exchange > /dev/null 2>&1
#      /usr/bin/zcat /var/tmp/pgsql.sql |psql -U pgsql -h 127.0.0.1 -f - asterisk > /dev/null 2>&1
#      /usr/sbin/crond >> /var/log/cron 2>&1
#      sed -e "s/#listen_addresses.*/listen_addresses = '*'/" -e "s/#ssl.*/ssl= on/" "/var/spool/pgsql/postgresql.conf" > /tmp/pg.cnf
#      cp /tmp/pg.cnf "/var/spool/pgsql/postgresql.conf"
#      rm /tmp/pg.cnf
#     else
#      echo "Upgrade Not Done !!!!"
#    fi;
#  fi;
