#!/bin/bash

if [ ! -e /etc/netsentry-version ];then
  echo "This script must be run on a valid server"
  exit 255
fi;

DIST="/mnt/dev"
BASE="/var/spool/distrotech"

#Touch some files that should not be updated just in case
touch /etc/autofs.conf /etc/dhcpd.conf /etc/freshclam.conf /etc/hosts /etc/mgetty.config /etc/popper.conf /etc/rsyncd.conf 
touch /etc/asterisk/agents.conf /etc/asterisk/iax.conf /etc/ppp/diald.scr /etc/ppp/ip-down /etc/ppp/options 
touch /etc/ppp/secret /etc/racoon/racoon.conf /etc/radiusclient/port-id-map /etc/radiusclient/radiusclient.conf 
touch /etc/radiusclient/servers /etc/rc.d/rc.mount /etc/rc.d/rc.tunnels /etc/squid/filter.cnf /etc/squid/filter.conf

#Rsync options
ROPTS="-avOHKzP --exclude-from=/var/spool/apache/htdocs/ns/config/exclude.nfs"
RROPTS="-R ${ROPTS}"
RTIMEOUT=60

RERR=0;
KERR=0;
DEFVER="10.10.1";
NOKERN=0;
RSYNCK=0;
UPDIST=0;
UMNT=0;
NOSYNC=0;

eval `cat /etc/netsentry-version`

if [ ! "${RSERV}" ];then
  RSERV="pbx.distrotech.co.za";
 else
  SERV=${RSERV}
fi

if [ ! -d /var/spool/rsync/programs ];then
  /usr/sbin/socktest ${SERV} 873 > /dev/null 2>&1 
  RES=$?
  if [ ${RES} != 0 ] && [ "${SERV}" != "127.0.0.1" ];then
    SERV=127.0.0.1
    /usr/sbin/socktest ${SERV} 873 > /dev/null 2>&1 
    RES=$?
  fi;
 else
  NOSYNC=1;
  RES=0;
fi;

if [ ${RES} != 0 ];then
  if [ ! -d /mnt/update ];then
    mkdir -p /mnt/update
  fi;
  vgchange -a y flash > /dev/null 2>&1
  mount -L UPGRADE /mnt/update -o ro> /dev/null 2>&1
  if [ $? != 0 ];then
    if [ -e /dev/cdrom ];then
       mount /dev/cdrom /mnt/cdrom -o ro > /dev/null 2>&1
       if [ $? == 0 ];then
         if [ -e /mnt/cdrom/flash.hdd ];then
           LOOP=`losetup -f`
           losetup ${LOOP} /mnt/cdrom/flash.hdd
           vgchange -a y flash > /dev/null 2>&1
           mount -L UPGRADE /mnt/update -o ro
           if [ $? != 0 ];then
             umount /mnt/cdrom
             echo "Needs local Upgrade Disk - No Upgrade Partition"
             exit 255;
           fi;
          else
           umount /mnt/cdrom
           echo "Update media not found"
           exit 255;
          fi;
        else
         echo "Update media not found"
         exit 255;
       fi;
     else
      echo "Update media not found"
      exit 255;
    fi;
  fi;
  if [ ! -d /mnt/update${DIST} ];then
    mkdir -p /mnt/update${DIST}
  fi;
  mount -L INSTALL /mnt/update${DIST} -o ro> /dev/null 2>&1
  if [ $? != 0 ];then
    umount /mnt/update
    echo "Needs local Upgrade Disk - No Install Partition"
    exit 255;
  fi;
  /usr/bin/rsync --daemon --config /mnt/update${DIST}/etc/rsyncd-update.conf > /dev/null 2>&1
  /usr/sbin/socktest  127.0.0.1 873 > /dev/null 2>&1 
  if [ $? != 0 ];then
    umount /mnt/update${DIST}
    umount /mnt/update
    echo "Needs local Upgrade Disk - Service Failure"
    exit 255;
  fi;
  RSYNCK=1;
  DUFS=`findfs LABEL=DTSUTIL`
  if [ ! "${DUFS}" ];then
    DUFS=`findfs LABEL=DISTROTECH`
  fi;
  if [ "${DUFS}" ];then
    dosfsck -a ${DUFS}
    mount ${DUFS} /mnt/update/${DIST}/install/tools -o ro
  fi; 
fi;

if [ "$1" == "" ];then
  NOKERN=1;
  if [ "$KERNEL" == "" ];then
    KERNEL=`uname -r |awk -F- '$2 == "i386" || $2 == "x86" {print $1"-"$2}'`
    if [ "$KERNEL" == "" ];then
      KERNEL=`uname -r |awk -F- '$3 == "i386"  || $3 == "x86" {print $1"-"$2"-"$3}'`  
    fi;
  fi;
 else
  KERNEL=$1
fi

if [ "$VERSION" == "" ];then
  LVERSION="${DEFVER}"
 else
  LVERSION=$VERSION
fi;

if [ ! "$KERNOPTS" ];then
  if [ "`uname -r |grep nosmp`" ] || [ -e "/etc/.bootnosmp" ];then
    KERNOPTS="nosmp"
  fi;
fi;

#Update netsentry-version
if [ "$1" != "" ];then
  (cat <<__EOF__
BRAND="$BRAND";
VERSION="$LVERSION";
KERNEL="$KERNEL";
SMP_KERNEL="\$KERNEL-smp";
INSTALL_KERNEL="\$KERNEL-install";
IP_ADDR="$IP_ADDR";
SN_ADDR="$SN_ADDR";
HN_ADDR="$HN_ADDR";
DOM_ADDR="$DOM_ADDR";
BT="\$BRAND V\$VERSION Linux V\$KERNEL Install";
KERNOPTS="$KERNOPTS";
EXTRA_DEV="$EXTRA_DEV";
USBSLEEP="$USBSLEEP";
RSERV="$RSERV";
__EOF__
) > /etc/netsentry-version
  touch /var/spool/apache/htdocs/ns/config/exclude.nfs
fi;

SMP_KERNEL="$KERNEL-smp";
INSTALL_KERNEL="$KERNEL-install";

KERNEX="--include=/$INSTALL_KERNEL \
        --include=/$SMP_KERNEL \
        --include=/[vS]*$INSTALL_KERNEL \
        --include=/[vS]*$SMP_KERNEL \
        --exclude=/*"

if [ ! -d ${DIST}/install ] && [ ${RSYNCK} == 0 ];then
  vgchange -a y flash > /dev/null 2>&1
  if [ -e /dev/flash/install ];then
    if [ ! -d ${DIST} ];then
      mkdir ${DIST}
    fi;
    e2fsck -p /dev/flash/install
    if (( $? < 4 ));then
      mount /dev/flash/install ${DIST}
      if [ $? == 0 ];then
        DUFS=`findfs LABEL=DTSUTIL`
        if [ ! "${DUFS}" ];then
          DUFS=`findfs LABEL=DISTROTECH`
        fi;
        if [ "${DUFS}" ];then
          dosfsck -a ${DUFS}
          mount ${DUFS} ${DIST}/install/tools
        fi; 
        UPDIST=1
        UMNT=1
      fi;
    fi;
  fi;
 elif [ -d ${DIST}/install ];then
  UPDIST=1
fi;

if [ ${NOSYNC} == 0 ];then
  #Old upgrade postgre to ver 8
#  if [ ! "`psql -V |head -1|grep "8.2.3"`" ];then
#    /usr/bin/pg_dumpall -U pgsql -h 127.0.0.1 -c |gzip -c > /var/tmp/pgsql.sql
#    if [ $? != 0 ];then
#      echo "Upgrade Not Done !!!!"
#      exit -1
#    fi;
#    /usr/bin/pg_dumpall -U postgres -p 5433 -h 127.0.0.1 -c |gzip -c > /var/tmp/cubit.sql
#    if [ $? != 0 ];then
#      echo "Upgrade Not Done !!!!"
#      exit -1
#    fi;
#    if [ -s /var/tmp/pgsql.sql ] && [ -s /var/tmp/cubit.sql ];then
#      /usr/bin/killall -9 crond > /dev/null 2>&1
#      /usr/bin/killall -9 asterisk > /dev/null 2>&1
#      /bin/su pgsql -c "pg_ctl -D /var/spool/pgsql -m immediate stop" > /dev/null 2>&1
#      /bin/su postgres -c "pg_ctl -D /var/spool/cubit -m immediate stop" > /dev/null 2>&1
#      /usr/bin/killall -9 postmaster > /dev/null 2>&1
#      /usr/bin/rsync $RROPTS --timeout=$RTIMEOUT ${SERV}::postgresql /
#      if [ $? != 0 ];then
#        echo "Upgrade Not Done !!!!"
#        exit -1
#      fi;
#      /bin/rm -rf /var/spool/pgsql
#      /bin/rm -rf /var/spool/cubit
#      /etc/rc.d/rc.exchange > /dev/null 2>&1
#      /usr/bin/zcat /var/tmp/pgsql.sql |psql -U pgsql -h 127.0.0.1 -f - asterisk > /dev/null 2>&1
#      /etc/rc.d/rc.cubit > /dev/null 2>&1
#      /usr/bin/sleep 5
#      /usr/bin/zcat /var/tmp/cubit.sql |psql -U postgres -h 127.0.0.1 -p 5433 -f - template1 > /dev/null 2>&1
#      /usr/sbin/crond >> /var/log/cron 2>&1
#      sed -e "s/#listen_addresses.*/listen_addresses = '*'/" -e "s/#ssl.*/ssl= on/" "/var/spool/pgsql/postgresql.conf" > /tmp/pg.cnf
#      cp /tmp/pg.cnf "/var/spool/pgsql/postgresql.conf"
#      rm /tmp/pg.cnf
#     else
#      echo "Upgrade Not Done !!!!"
#    fi;
#  fi;

  if [ ${UPDIST} == 1 ];then
    if [ ! -f ${DIST}/install/core/filelist ];then
      rsync $RROPTS --timeout=$RTIMEOUT --include=/install/netsentry-version --include=/install/core/filelist --include=/install/core \
            --exclude=/install/core/* --exclude=/install/* ${SERV}::base/install/* ${DIST}
      if [ -e ${DIST}/install/core/filelist ];then
        grep -vE "(^sys)|(^dev)|(^proc)|(/$)" ${DIST}/install/core/filelist > /tmp/filelist
        cd /
        tar --use-compress-program=bzip2 -T /tmp/filelist  -cf ${DIST}/install/core/install.tbz
        cd
        rm /tmp/filelist
        tar -C ${DIST} --use-compress-program=bunzip2 -xf ${DIST}/install/core/install.tbz
        rsync $RROPTS --timeout=$RTIMEOUT --exclude=/install --exclude=/boot --exclude=/lib/modules ${SERV}::install ${DIST}
        NOKERN=0
      fi;
    fi;

    echo "install/ ${DIST}/"
    rsync ${RROPTS} --delete --exclude=/proc --exclude=/sys --exclude=/lost+found --exclude=/dev --exclude=/install/mnt \
	--exclude=install/avirus --exclude=/lib/modules/ --exclude=/install/core --exclude=/boot/initrd-install* \
	--exclude=/mnt/update --include=/boot/grub/background.jpg --exclude=/boot/grub/* --exclude=/etc/mtab --exclude=/install/netsentry-version \
	--exclude=/boot/vmlinuz-install --exclude=/boot/System.map-install --timeout=$RTIMEOUT ${SERV}::install/ ${DIST}/
    echo;echo
  fi;

  if [ -e /etc/asterisk/version.10 ];then
    ast_repo="asterisk-10";
   else
    ast_repo="asterisk";
  fi;

  for rdatain in "vbox /"  "share /var/spool/samba/share/" "programs /" "manuals /var/spool/apache/htdocs/" "${ast_repo} /" "avirus /var/spool/avirus";do 
    echo $rdatain
    rsync $RROPTS -u --delay-updates --timeout=$RTIMEOUT ${SERV}::$rdatain
    if [ $? != 0 ];then
      RERR=255;
    fi;
    echo;echo
  done;

  #Sync Asterisk Modules
  if [ -e /etc/asterisk/version.10 ];then
    rsync $RROPTS -u --delay-updates --delete --exclude=chan_lcr.so --timeout=$RTIMEOUT ${SERV}::asterisk-10/usr/lib/asterisk/modules-10 /
   else
    rsync $RROPTS -u --delay-updates --delete --exclude=chan_lcr.so --timeout=$RTIMEOUT ${SERV}::asterisk/usr/lib/asterisk/modules-1.8 /
  fi;
  if [ $? != 0 ];then
    RERR=255;
  fi;

  #Update kernel
  if [ "$NOKERN" != "1" ];then
    if [ ${UPDIST} == 1 ];then
      if [ -d ${DIST}/lib/modules/${INSTALL_KERNEL} ];then
        rsync $ROPTS --delete --exclude=/modules.* ${DIST}/lib/modules/${INSTALL_KERNEL}/* /lib/modules/${INSTALL_KERNEL}/
      fi;
      if [ ! -d /var/spool/rsync/kernuser ];then
        mkdir -p /var/spool/rsync/kernuser
      fi;
      rsync $ROPTS --delete --timeout=$RTIMEOUT ${SERV}::kernuser/kernel-${SMP_KERNEL} /var/spool/rsync/kernuser/
      if [ $? != 0 ];then
        KERR=1;
      fi;
      if [ ${KERR} == 0 ];then
        rsync $ROPTS /var/spool/rsync/kernuser/kernel-${SMP_KERNEL}/* /
      fi;
     else
      echo kernuser/kernel-${SMP_KERNEL}/* /
      rsync $ROPTS --timeout=$RTIMEOUT ${SERV}::kernuser/kernel-${SMP_KERNEL}/* /
      if [ $? != 0 ];then
        KERR=1;
      fi;
    fi;
    for rdatain in "kernel/* /boot/" "kernmod/* /lib/modules/";do
      echo $rdatain
      rsync $ROPTS $KERNEX --timeout=$RTIMEOUT ${SERV}::$rdatain
      if [ $? != 0 ];then
        KERR=1;
      fi;
    done;

    if [ $KERR != 0 ];then
      RERR=$KERR;
    fi;
  fi;
fi;

#Remove local media
if [ $RSYNCK == 1 ];then
  while [ `pidof rsync` ];do
    killall rsync
    sleep 1
  done
  (umount /mnt/update/${DIST}/install/tools
  umount /mnt/update${DIST}
  umount /mnt/update) > /dev/null 2>&1
  if [ "${LOOP}" ];then
    vgchange  -a n flash > /dev/null 2>&1
    sleep 2
    losetup -d ${LOOP}
    umount /mnt/cdrom
  fi;
  UPDIST=0;
fi;

#Final processing on no error
if [ ${RERR} == 0 ];then
  /usr/bin/rebuild-info
#  pear channel-update pear.php.net;pear upgrade-all

  #Run any SQL / LDAP scripts on no error
  if [ -d /var/spool/update ];then
    for I in /var/spool/update/*.sql ; do
      if test $I -nt /etc/asterisk/astschema.psql.gz ;then
        cat $I |psql -U asterisk -h 127.0.0.1
      fi
    done;
    touch /etc/asterisk/astschema.psql.gz

    for I in /var/spool/update/*.esql ; do
      if test $I -nt /var/spool/pgsql/exchange.db ;then
        cat $I |psql -U exchange -h 127.0.0.1
      fi
    done;
    touch /var/spool/pgsql/exchange.db

    if [ /var/spool/update/remote.keys -nt /root/.ssh/authorized_keys ] || [ ! -e /root/.ssh/authorized_keys ] || [ ! -s /root/.ssh/authorized_keys ];then
      (/usr/bin/ldapmodify -U admin -Y PLAIN -w "`cat /etc/mail/ldap`" -cf /var/spool/update/remote.keys
      /usr/bin/gensshauth > /root/.ssh/authorized_keys.tmp
      if [ ! -d /root/.ssh ];then
        mkdir /root/.ssh
        chmod 700 /root/.ssh
      fi;
      if [ -s /root/.ssh/authorized_keys.tmp ];then
        cp /root/.ssh/authorized_keys.tmp /root/.ssh/authorized_keys
      fi) > /dev/null 2>&1
    fi;
  fi;

  ldconfig
  /usr/sbin/genconf
  /usr/sbin/asterisk -rx "dialplan reload"

  #Reinstall Grub/Update initrd if needed
  if [ ! -e /boot/grub/core.img ] || [ /usr/lib/grub/i386-pc/ -nt /boot/grub/core.img ];then
    /usr/sbin/mkgrub
   elif [ $NOKERN != 1 ] && [ $KERR == 0 ];then
    /usr/sbin/mkinitrd
   elif [ /usr/sbin/mkinitrd -nt /boot/initrd-netsentry ] && [ $KERR == 0 ];then
    /usr/sbin/mkinitrd
  fi
  if [ ${UPDIST} == 1 ];then
    if [ ! -e ${DIST}/install/core/kernel.tar.bz2 ] || [ /boot/vmlinuz-${INSTALL_KERNEL} -nt ${DIST}/install/core/kernel.tar.bz2 ];then
      ${DIST}/install/tarkernel ${KERNEL}
     elif [ -e ${DIST}/install/.version ];then
      VERSION=`cat ${DIST}/install/.version`;
      sed -e "s/\(VERSION=\"\).*/\1${VERSION}\";/" ${DIST}/install/netsentry-version > /tmp/netsentry-version
      if [ "`diff /tmp/netsentry-version ${DIST}/install/netsentry-version`" ];then
        mv /tmp/netsentry-version ${DIST}/install/netsentry-version
       else
        rm /tmp/netsentry-version
      fi;
    fi;

    (rsync -avP /var/spool/avirus/*.* ${DIST}/install/avirus/
    rsync -avP /var/spool/rsync/programs/var/spool/update ${DIST}/install/ ) > /dev/null 2>&1
    ${DIST}/install/flashutil iso /var/spool/samba/ftp/distrotech.iso
  fi;
 else
  ldconfig
  /usr/sbin/genconf
  /usr/sbin/asterisk -rx "dialplan reload"
fi;

if [ ${UMNT} == 1 ];then
  umount ${DIST}/dev ${DIST}/proc ${DIST}/sys ${DIST}
  vgchange -a n flash
  if [ "${LOOP}" ];then
    sleep 2
    losetup -d ${LOOP}
  fi;
fi;

exit $RERR
