#!/bin/bash

eval `cat /etc/netsentry-version`

if [ "${RSERV}" == "127.0.0.1" ] && [ "$1" == "" ];then
  echo "No Useable Server Supplied"
  exit;
fi

if [ "$1" != "" ];then
  sed -e "s/^RSERV.*/RSERV=\"$1\";/" /etc/netsentry-version > /tmp/netsentry-version
  cp /tmp/netsentry-version /etc/netsentry-version
  RSERV=$1
fi;

/usr/bin/ssh -f -L 873:127.0.0.1:873 ${RSERV} sleep 600
if [ "$?" == "0" ];then
  /usr/sbin/vbox_upgrade 2.6.33.5-x86
 else
  echo "Connect Failed"
fi;

