#!/usr/bin/php -d safe_mode = off
<%
/*
#    Copyright (C) 2002  <Gregory Hinton Nietsky>
#    Copyright (C) 2005  <ZA Telecomunications>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

include "/var/spool/apache/htdocs/ldap/ldapcon.inc";
include "/var/spool/apache/htdocs/cdr/auth.inc";
include "/var/spool/apache/htdocs/cdr/voiptls.inc";

ldap_bind($ds,$LDAP_ROOT_DN,$LDAP_ROOT_PW);

if ($argc < 2) {
  print "Usage Is $argv[0] [-C <TYPE>]|[-c <exten>]|[-n <exten>][-D]|[-d <exten>]|[-g <exten>]\n";
  print " -C Create All For Type ie SNOM\n";
  print " -c Create A Extension\n";
  print " -n [New] Delete / Create A Extension\n";
  print " -D Delete All\n";
  print " -d Delete A Extension\n";
  print " -g Get User Cert\n";
} else {
  switch($argv[1]) {
    case "-D":delete_allexten_x509();
      break;
    case "-d":delete_exten_x509($argv[2]);
      break;
    case "-C":create_phone_x509($argv[2]);
      break;
    case "-c":create_exten_x509($argv[2]);
      break;
    case "-n":delete_exten_x509($argv[2]);
        create_exten_x509($argv[2]);
      break;
    case "-g":print dump_phone_x509($argv[2]);
      break;
  }
}
%>
