#!/usr/bin/perl


$type=shift(@ARGV);
$name=lc(shift(@ARGV));
$nbnum=shift(@ARGV);
$ttl=shift(@ARGV);


if ($type eq "refresh") {
  $type="add";
}

open(OP,"|/usr/bin/nsupdate > /dev/null");

print OP<<__EOB__;
server 127.0.0.1
zone distrotech.co.za
key distrotech.co.za bWFrZW1lc21hcnQ=
__EOB__

if ($type ne "delete") {
  print OP "update delete " . $name . " A\n";
}

foreach $ipaddr (@ARGV) {
  if ((index($ipaddr,"127.0.0.") < 0) && ($ipaddr != "255.255.255.255")){
    print OP "update " . $type . " " . $name . " " . $ttl . " A " . $ipaddr . "\n";
  }
}
print OP "send\n";

foreach $ipaddr (@ARGV) {
  if ((index($ipaddr,"127.0.0.") < 0) && ($ipaddr != "255.255.255.255")){
    @ipdat=split(/\./,$ipaddr);
    $rev=@ipdat[2] . "." . @ipdat[1] . "." . @ipdat[0] . ".in-addr.arpa";
    print OP <<__EOB__;
server 127.0.0.1
zone $rev
key distrotech.co.za bWFrZW1lc21hcnQ=
update delete @ipdat[3] PTR
update $type @ipdat[3] $ttl PTR $name.distrotech.co.za.
send
__EOB__
  }
}

close(OP);
