#!/mnt/usr/bin/perl -I /mnt/usr/lib/perl5

open(FL,"-");
$cnt=0;
$percl=0;
while(<FL>)
  {
    $cnt++;
    ($perc)=split(/\./,(($cnt/$ARGV[0])*100));
    if ($perc > $percl)
      {
        printf(<STDOUT>,"$perc\n");
      }
    $percl=$perc;
  }
close(FL);
