#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin

Make_InstallRD() {
  LOOP=`losetup -f`
  if [ ! "${LOOP}" ] || [ ! -e "${LOOP}" ];then
    return 255
  fi;

  (dd if=/dev/zero of=/tmp/initrd bs=1M count=${2}
  losetup ${LOOP} /tmp/initrd
  mkfs.ext2 -F -L initrd -i 1024 /tmp/initrd
  mount ${LOOP} /mnt/initrd) > /dev/null 2>&1

  for tld in bin dev etc isofs lib proc sbin sys sysroot var;do
    mkdir /mnt/initrd/${tld}
  done

  mkdir -p /var/lock/lvm
  mkdir /mnt/initrd/etc/lvm
  for lvmdir in archive backup cache;do
    mkdir /mnt/initrd/etc/lvm/${lvmdir}
  done;

  cp /etc/lvm/lvm.conf /mnt/initrd/etc/lvm/
  cp /usr/sbin/lvm.static /mnt/initrd/sbin/lvm
  cp /usr/bin/modprobe.static /mnt/initrd/sbin/modprobe
  cp /sbin/nash /mnt/initrd/bin
  cp /sbin/losetup.static /mnt/initrd/sbin/losetup
  cp /sbin/mount.static /mnt/initrd/bin/mount
  ln -s /proc/mounts /mnt/initrd/etc/mtab
  ln -s /sbin/lvm /mnt/initrd/sbin/vgchange
  ln -s /sbin/lvm /mnt/initrd/sbin/vgscan
  ln -s /sbin/lvm /mnt/initrd/sbin/vgmknodes
  ln -s /linuxrc /mnt/initrd/sbin/init
  touch /mnt/initrd/etc/fstab

  mkdir -p /mnt/initrd/lib/modules/${1}/
  for drvsub in drivers drivers-ata  drivers-usb;do
    mkdir /mnt/initrd/lib/modules/${1}/${drvsub}
  done

  cp -r /lib/modules/${1}/kernel/drivers/ata/* /lib/modules/${1}/kernel/drivers/mmc/host/* /mnt/initrd/lib/modules/${1}/drivers-ata
  mv /mnt/initrd/lib/modules/${1}/drivers-ata/ata_generic.ko.gz \
     /mnt/initrd/lib/modules/${1}/drivers-ata/pata_legacy.ko.gz \
     /mnt/initrd/lib/modules/${1}/drivers-ata/ahci_platform.ko.gz \
     /mnt/initrd/lib/modules/${1}/drivers-ata/pata_acpi.ko.gz \
     /mnt/initrd/lib/modules/${1}/drivers-ata/libahci.ko.gz \
     /mnt/initrd/lib/modules/${1}/drivers

  cp -r /lib/modules/${1}/kernel/drivers/usb/storage/* /mnt/initrd/lib/modules/${1}/drivers-usb
  cp /lib/modules/${1}/kernel/lib/crc-t10dif.ko.gz /mnt/initrd/lib/modules/${1}/drivers

   for kmod in block/loop.ko.gz md/dm-mod.ko.gz base/firmware_class.ko.gz "pcmcia/*" "mmc/core/*" \
       "mmc/card/*" "misc/cb710/*" misc/tifm_core.ko.gz cdrom/cdrom.ko.gz "ssb/*" "usb/host/*";do
    cp -r /lib/modules/${1}/kernel/drivers/${kmod} /mnt/initrd/lib/modules/${1}/drivers
   done;

  for kmod in isofs/isofs.ko.gz nls/nls_iso8859-1.ko.gz "ext*/*" "jbd*/*";do
    cp -r /lib/modules/${1}/kernel/fs/${kmod} /mnt/initrd/lib/modules/${1}/drivers
  done;

  for kmod in scsi_mod.ko.gz sd_mod.ko.gz sr_mod.ko.gz;do
    cp -r /lib/modules/${1}/kernel/drivers/scsi/${kmod} /mnt/initrd/lib/modules/${1}/drivers
  done;

  /sbin/depmod -b /mnt/initrd -aeF /boot/System.map-install ${1}

  (cat << EOF
options loop max_part=63
options sg allow_dio=1
EOF
) > /mnt/initrd/etc/modprobe.conf

  (cat << EOF
#!/bin/bash

gunzip -c /install/core/etc.gz |dd of=/dev/ram5 > /dev/null 2>&1
mount -n -t ext4 /dev/ram5 /etc
EOF
) > /mnt/initrd/sbin/mntetc
  chmod 750 /mnt/initrd/sbin/mntetc
}

Make_InitRD_CFG() {
  (cat << EOF
#!/bin/nash

mount -t ramfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

mknod /dev/console c 5 1
mknod /dev/urandom c 1 9
mknod /dev/null c 1 3
mknod /dev/systty c 4 0
mknod /dev/zero c 1 5
mknod /dev/ram5 b 1 5
mknod /dev/loop0 b 7 0
mknod /dev/cdrom b 11 0

EOF
)

for driver in `ls -s /mnt/initrd/lib/modules/${1}/drivers-ata/* |cut -d/ -f8 |cut -d. -f1`;do
  echo "modprobe ${driver}"
done;

  (cat << EOF

modprobe pata_acpi
modprobe ata_generic
modprobe uhci_hcd
modprobe ohci_hcd
modprobe ehci_hcd
EOF
)

for driver in `ls -s /mnt/initrd/lib/modules/${1}/drivers-usb/* |cut -d/ -f8 |cut -d. -f1`;do
  echo "modprobe ${driver}"
done;

  (cat << EOF
modprobe sd_mod
modprobe sr_mod
modprobe cdrom
modprobe loop
modprobe dm-mod

sleep 10
EOF
)

  if [ "${2}" == "dvd" ];then
    (cat << EOF

/bin/mount -n -o ro -t iso9660 -L DISTROTECH_INSTALL /isofs
/sbin/losetup /dev/loop0 /isofs/flash.hdd
EOF
)
  fi;

  (cat << EOF

mkdevices /dev
mkdmnod
vgchange -a y --sysinit
vgmknodes
/bin/mount -o ro -n -t ext4 -L INSTALL /sysroot
echo 0x0100 > /proc/sys/kernel/real-root-dev

pivot_root /sysroot /sysroot/initrd

mount -t ramfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mkdir /dev/udevdb
mkdir /dev/pts
mkdir /dev/shm
mount -t devpts none /dev/pts
udevstart
/initrd/sbin/mntetc
EOF
)
}

eval `cat /install/netsentry-version`
depmod -a -F /boot/System.map-install ${KERNEL}-install

Make_InstallRD ${KERNEL}-install 8
if [ $? != 0 ];then
  exit
fi;

Make_InitRD_CFG ${KERNEL}-install > /mnt/initrd/linuxrc
chmod 750 /mnt/initrd/linuxrc
sleep 2
umount /mnt/initrd
e2fsck -Dfy ${LOOP}
dd if=/tmp/initrd |gzip -c9 > /boot/initrd-install

mount ${LOOP} /mnt/initrd
Make_InitRD_CFG ${KERNEL}-install dvd > /mnt/initrd/linuxrc
chmod 750 /mnt/initrd/linuxrc
sleep 2
umount /mnt/initrd
e2fsck -Dfy ${LOOP}
dd if=/tmp/initrd |gzip -c9 > /boot/initrd-install-dvd

sleep 2
losetup -d ${LOOP}
rm /tmp/initrd
rm -rf /mnt/initrd/*
