#!/bin/bash

DIST="/mnt/dev"

if [ -e  ${DIST}/install/netsentry-version ];then
  eval `cat ${DIST}/install/netsentry-version`

  if [ -d /var/spool/rsync/kernuser/kernel-${SMP_KERNEL} ];then
    cd /var/spool/rsync/kernuser/kernel-${SMP_KERNEL}
    tar --use-compress-program=bzip2 -cf ${DIST}/install/core/kernel.tar.bz2 * /lib/modules/${SMP_KERNEL} /boot/[vS]*${SMP_KERNEL}

    rsync -avP /lib/modules/${INSTALL_KERNEL} ${DIST}/lib/modules
    rsync -avP /boot/vmlinuz-${INSTALL_KERNEL} ${DIST}/boot/vmlinuz-install
    rsync -avP /boot/System.map-${INSTALL_KERNEL} ${DIST}/boot/System.map-install
   else
    echo "No kernel folder";
    exit -1
  fi;
 else
  echo "No config file";
  exit -1
fi;
