#!/bin/bash

#    Copyright (C) 2002  <Gregory Hinton Nietsky>
#    Copyright (C) 2005  <ZA Telecomunications>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#Start UP TDM Channels
if [ -e /usr/sbin/dahdi_cfg ];then
  TDM_CFG="/usr/sbin/dahdi_cfg"
  TDM_REV="/etc/dahdi/systemr.conf";
  if [ -s ${TDM_REV} ];then
    (${TDM_CFG}
    /usr/bin/sleep 30
    ${TDM_CFG} -c ${TDM_REV}
    /usr/bin/sleep 30
    ${TDM_CFG}) > /dev/null 2>&1 &
   else
    ${TDM_CFG} > /dev/null 2>&1
  fi;
fi;

#Set Echo Coefficients
if [ -d /proc/dahdi ];then
  if [  "`cat /proc/dahdi/* 2>/dev/null |grep FXSKS`" ];then
    if [ -e /etc/fxotune.conf ];then
      /usr/sbin/fxotune -s > /dev/null 2>&1
     else
      echo "Initiating ZAP FXO Coefficients";
      /usr/sbin/fxotune -i 0
    fi;
  fi;  
fi;
