#!/bin/bash

#    Copyright (C) 2002  <Gregory Hinton Nietsky>
#    Copyright (C) 2005  <ZA Telecomunications>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#Configure ippools
/usr/sbin/ippoold >/tmp/ippool.out 2>&1
(/usr/bin/sleep 1
for ippool in /etc/ippool/* ;do
  /usr/bin/ippoolconfig "config  restore  file=${ippool}"
done) > /dev/null 2>&1

#Startup daemon
if [ ! -e /etc/openl2tpd.conf ] && [ -e /etc/openl2tpd.conf.orig ];then
  cp /etc/openl2tpd.conf.orig /etc/openl2tpd.conf
fi;   
if [ -e /var/run/openl2tpd.pid ];then
  rm /var/run/openl2tpd.pid
fi;
if [ -e /etc/openl2tpd.conf ];then
  openl2tpd -p ipsec.so > /dev/null 2>&1
fi;
