#!/bin/bash

#    Copyright (C) 2002  <Gregory Hinton Nietsky>
#    Copyright (C) 2005  <ZA Telecomunications>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#Enable Advanced Routing
if [ ! -e /etc/quagga/Quagga.conf ];then
  cp /etc/quagga/Quagga.conf.orig /etc/quagga/Quagga.conf
fi;
(for prog in zebra ripd ripngd ospfd ospf6d babeld bgpd isisd;do
  rm /var/run/$prog.*
  $prog -d
done;
/usr/bin/vtysh -b) > /dev/null 2>&1
